//
// Hershey Font: gothitt 
//
// USE RESTRICTION:
//    This distribution of the Hershey Fonts may be used by anyone for
//    any purpose, commercial or otherwise, providing that:
//
//        1. The following acknowledgements must be distributed with the font data:
//
//            - The Hershey Fonts were originally created by Dr.
//                A. V. Hershey while working at the U. S. National Bureau of Standards.
//            - The format of the Font data in this distribution was originally created by
//                James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821,
//               (mit-eddie!ci-dandelion!hurt)
//
//        2. The font data in this distribution may be converted into
//            any other format *EXCEPT* the format distributed by
//            the U.S. NTIS (which organization holds the rights
//            to the distribution and use of the font data in that
//            particular format). Not that anybody would really
//            *want* to use their format... each point is described
//            in eight bytes as "xxx yyy:", where xxx and yyy are
//            the coordinate values as ASCII numbers.
//

const char glyph032[] PROGMEM = "\x00" "JZ";
const char glyph033[] PROGMEM = "\x1d" "LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY";
const char glyph034[] PROGMEM = "\x15" "I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM";
const char glyph035[] PROGMEM = "\x0b" "H]SFLb RYFRb RLQZQ RKWYW";
const char glyph036[] PROGMEM = "\x3b" "H\\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMNOOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[";
const char glyph037[] PROGMEM = "\x1f" "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
const char glyph038[] PROGMEM = "\x3d" "E_YNZO[O\\N RXOYP[P RXPYQZQ[P\\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[Z[[Z\\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\\X";
const char glyph039[] PROGMEM = "\x0d" "LXRLRJPHRFSHSJRLPM RRGQHRIRG";
const char glyph040[] PROGMEM = "\x1a" "KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\\ RSDRFQIPOPUQ[R^S`";
const char glyph041[] PROGMEM = "\x1a" "KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\\ RQDRFSITOTUS[R^Q`";
const char glyph042[] PROGMEM = "\x26" "JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO RWIMO RWIWJMNMO";
const char glyph043[] PROGMEM = "\x0f" "F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R";
const char glyph044[] PROGMEM = "\x0d" "LXR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
const char glyph045[] PROGMEM = "\x07" "F_JQ[Q[R RJQJR[R";
const char glyph046[] PROGMEM = "\x0a" "LXRXPZR[TZRX RRYQZSZRY";
const char glyph047[] PROGMEM = "\x07" "G^[BIbJb R[B\\BJb";
const char glyph048[] PROGMEM = "\x29" "H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJYLYNZO[QZVYXY";
const char glyph049[] PROGMEM = "\x1a" "H\\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY";
const char glyph050[] PROGMEM = "\x2f" "H\\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ RK[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY";
const char glyph051[] PROGMEM = "\x38" "H\\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVRXRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
const char glyph052[] PROGMEM = "\x28" "H\\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVXXYYY RRYSYUZV[WZYY";
const char glyph053[] PROGMEM = "\x34" "H\\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWMYNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
const char glyph054[] PROGMEM = "\x3a" "H\\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOPSOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY";
const char glyph055[] PROGMEM = "\x25" "H\\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ RUMSPRSRVSYQ[";
const char glyph056[] PROGMEM = "\x46" "H\\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO RLONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[QZVYXY";
const char glyph057[] PROGMEM = "\x3b" "H\\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZHXIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY";
const char glyph058[] PROGMEM = "\x15" "LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY";
const char glyph059[] PROGMEM = "\x18" "LXRMPORPTORM RRNQOSORN RR^R\\PZRXSZS\\R^P_ RRYQZR[RY";
const char glyph060[] PROGMEM = "\x03" "F^ZIJRZ[";
const char glyph061[] PROGMEM = "\x0f" "F_JM[M[N RJMJN[N RJU[U[V RJUJV[V";
const char glyph062[] PROGMEM = "\x03" "F^JIZRJ[";
const char glyph063[] PROGMEM = "\x32" "I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVMUOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY";
const char glyph064[] PROGMEM = "\x37" "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
const char glyph065[] PROGMEM = "\x33" "E_NHLIJKIMHPHSIUKV RJLIOISJU RNHLJKLJOJRKVKXJZH[ RVHXHXYVY RYHYY RZGZZ RHFKGQHVHZG\\F RJPXP RH[KZQYVYZZ\\[";
const char glyph066[] PROGMEM = "\x40" "E_LGLZ RMGMZ RPFNGNZP[ RHJJHLGPFUFXGZIZKYM RXHYIYKXM RUFWGXIXKWL RQUOTNRNPONPMSLVLYM[O\\Q\\T[WYYWZT[P[LZJYHW RZO[Q[UZW RVLYNZQZUYXWZ";
const char glyph067[] PROGMEM = "\x3b" "E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS";
const char glyph068[] PROGMEM = "\x2d" "E_KGKZ RLGLZ RNFMGMZN[ RHKIIKGNFSFVGXHZJ[L\\O\\R[UZWXYVZS[N[KZIXHV RZK[N[SZV RVGXIYKZNZSYVXXVZ";
const char glyph069[] PROGMEM = "\x55" "E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\\[ R[HZMZT[Y RZKYJ RZMXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS RJPKONOUQXQZP RPPRQURWRYQ RMORRUSWSYRZP RZMYLXLWMXNYM";
const char glyph070[] PROGMEM = "\x44" "E_JHJZ RMGKHKY ROFMGLILYNY RHJJHLGOFSFVGXHYI\\F R\\F[HZLZO[S\\U RZIYK RVGXIYLZO RLPMOOOTPWPYO RQPTQVQXP RNOTRVRXQYOYLXKWKVLWMXL RH[JZNYSYYZ\\[";
const char glyph071[] PROGMEM = "\x59" "E_\\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[T[VZXYYXZV[Y\\[ R[HZMZT[Y RZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RXXYVYR RVZWYXVXQ RKSLRMSLTKTJS RJPKNMMOMRNUPWQ RKOMNONROTP RJPLOOOUQYQZP";
const char glyph072[] PROGMEM = "\x31" "E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKVKYL[N\\Q\\T[UYV RZN[P[SZU RVKXLYMZOZSYVYXZZ\\[ RH[LZPZU[";
const char glyph073[] PROGMEM = "\x16" "E_QIQY RRJRX RSISY RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
const char glyph074[] PROGMEM = "\x29" "E_TIVIVXUZS[ RWIWXVY RXHXY RHFLHPITIXH\\F RIOHQHUIXKZN[S[VZXYZW\\T RIUJXKY RHSJUKXLZN[";
const char glyph075[] PROGMEM = "\x45" "E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\\F RLPMNOLRKUKXLYMYOXPSRQSPTPUQVRUQT RWLXMXOWP RUKWMWOVPSR RSRVRYSZUZWYX RWSYUYW RSRVSXUYXZZ[[\\[ RH[LZPZU[";
const char glyph076[] PROGMEM = "\x2c" "E_JGJZ RKHKY RNHLHLYNY R\\KZNYPXSXUYW[X RZOYRYUZW R\\K[MZQZT[X\\[ RHFJGNHSHYG\\F RH[JZNYSYYZ\\[";
const char glyph077[] PROGMEM = "\x43" "E_QIQY RRJRX RSISY RNYLWJVIUHRHMIJKHMGPFTFWGYH[J\\M\\R[UZVXWVY RJUIRIMJJ RLWKUJRJLKIMG RZJ[M[RZU RWGYIZLZRYUXW RHFLHPITIXH\\F RH[KZOYUYYZ\\[";
const char glyph078[] PROGMEM = "\x2f" "E_JHJZH[ RLHKIKZ ROFMGLILZ RHJJHLGOFSFVGXHZJ[L\\O\\S[UYV RZK[N[RZU RVGXIYKZNZRYVYXZZ[[\\[ RH[LZPZU[";
const char glyph079[] PROGMEM = "\x35" "E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG";
const char glyph080[] PROGMEM = "\x32" "E_JIJZ RMHKJKY RQFOGMILKLYNY RHKJINGQFTFWGYH[J\\M\\O[RYTVURUOTMRLO RZJ[L[PZR RWGYIZLZPYSVU RH[JZNYSYYZ\\[";
const char glyph081[] PROGMEM = "\x49" "E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXHVGSFQF RJKINISJV RNGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG RJSKUNVTW[W\\X\\Z[[[Z\\Y RPWRW RKUNWQXSXTW";
const char glyph082[] PROGMEM = "\x44" "E_JIJZH[ RKIKZ RLHLZ RHKJILHNGQFUFYG[I\\K\\N[PZQ RYHZI[K[NZP RUFWGYIZKZOYQ RXRUSRSPRPPROUOXPZR\\U\\W[XZX RXQYR[V[WZT RTOVPXRYTZX[Z\\[ RH[LZPZU[";
const char glyph083[] PROGMEM = "\x5d" "E_TFZG\\F[H[JYHWGTFPFMGJJIMIOJRLTOURUTTUSVQVP R[GZH[J RJPKRLSOTRTTS RKIJKJNKPMRPSRSTRVPWOXO RLQMQNPPNRMUMWNYPZRZUYXWZ RPMRLULXMZO[R[UZW RIWJYIZ RNPNOOMPLRKUKXL[O\\R\\T[WYYWZT[P[MZKYIWIYH[JZP[";
const char glyph084[] PROGMEM = "\x41" "E_QHMHKIJJILHOHSIVJXKYMZP[S[VZXYZW[U\\R\\N[KYIWH RUHTITKULVKUJ RISJVLXNYQZTZWY RJJINIQJTLWNXQYTYWXYW[T\\R RHFKI RKHLG RIGJGKFMGQHWHZG\\F";
const char glyph085[] PROGMEM = "\x32" "E_LHJJILHOHRIUJWLYNZQ[U[XZZY RKJJLIOISJV RKILJLKKMJPJSKVLXNZ RVHXHXXWZU[ RYHYXXY RZGZY\\[ RHFKGQHVHZG\\F";
const char glyph086[] PROGMEM = "\x1e" "E_HFR[ RIGJHQWRY RJGKHRWSX R\\FR[ RWNUS RYLUQTTTV RHFJGOHUHZG\\F";
const char glyph087[] PROGMEM = "\x42" "E_LHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\\R\\O[LZJXH RJLIOIRJUKW RJJKKKLJOJRKVLXNZ RYWZU[R[OZL RVZXXYVZRZOYLYKZJ RQIQ[ RRJRZ RSIS[ RHFLHPITIXH\\F";
const char glyph088[] PROGMEM = "\x28" "E_HFXYYZ RIGKHZZ RLH\\[ R\\FSP RQRJZ RPSMULW RQRMTLUKWKY RHFLHPITIXH\\F RH[JZNYSYYZ\\[";
const char glyph089[] PROGMEM = "\x2e" "E_XHXZ RYHYY RZGZY RKHIJHMHPISKUMVPWSWVVXU RLUOVUV RHPIRKTNUTUVV RHFLHPITIXH\\F RHWJYLZP[T[XZ\\X";
const char glyph090[] PROGMEM = "\x48" "E_HFIGKHNHSFVFYGZIZKYM RXGYIYKXM RVFWGXIXL RXNTOROPNPLRKTKXL RTKVLWMVNTO RYM[O\\R\\T[WYYWZT[P[MZKYIWHTHRIOJNLMNMPNPPOQNPOO RXMZO[Q[UZW RXNYOZQZUYXWZ";
const char glyph091[] PROGMEM = "\x0b" "KYOBOb RPBPb ROBVB RObVb";
const char glyph092[] PROGMEM = "\x02" "KYKFY^";
const char glyph093[] PROGMEM = "\x0b" "KYTBTb RUBUb RNBUB RNbUb";
const char glyph094[] PROGMEM = "\x0a" "JZPLRITL RMORJWO RRJR[";
const char glyph095[] PROGMEM = "\x02" "JZJ]Z]";
const char glyph096[] PROGMEM = "\x0d" "LXTFRGQIQKRMTKRIRG RRJRLSKRJ";
const char glyph097[] PROGMEM = "\x29" "J[PQMTMXP[TY RNTNXPZ ROROWRZ RRSMNNMONNO RONSNUMWOWXXY RUNVOVXUYVZWYVX RSNUPUXTYV[XY";
const char glyph098[] PROGMEM = "\x1e" "IZNHLFMJMXP[UYWX RNHNXPZ RNHPFOJOWRZ ROOTMWPWX RTNVPVX RRNUQUY";
const char glyph099[] PROGMEM = "\x16" "KWNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMVOTPRN RSNUO";
const char glyph100[] PROGMEM = "\x1f" "JZRMMPMXP[RZUYWY RNPNXPZ ROOOWRZ RPIPFQIWPWY RPIVPVX RPIMIPJUPUY";
const char glyph101[] PROGMEM = "\x18" "KXNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMWQPU RSNVQ RRNUR";
const char glyph102[] PROGMEM = "\x1f" "KWOIOXNYP[ RPIPXOYPZQYPX RQHQXRYP[ ROIUFWHUISG RTGVH RLMOM RQMUM";
const char glyph103[] PROGMEM = "\x28" "J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW]V_U`SaQaO`MaObQa RTNVPV]U_ RPaNa RRNUQU^T`Sa";
const char glyph104[] PROGMEM = "\x29" "I[NHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROORNTMWPWYT]T`UbVbT` RTNVPVYU[ RRNUQUZT]";
const char glyph105[] PROGMEM = "\x24" "MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQXPYR[ RRPSORNQORPRXQYRZSYRX RRMTOSPSXTYR[";
const char glyph106[] PROGMEM = "\x24" "MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQYT] RRPSORNQORPRYS[ RRMTOSPSZT]T`RbPaPbRb";
const char glyph107[] PROGMEM = "\x32" "IZNHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROPRNTMVPSROU RSNUP RRNTQ RRSSTTYV[XY RSSTUUYVZ RSRTSVXWYXY";
const char glyph108[] PROGMEM = "\x14" "MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[";
const char glyph109[] PROGMEM = "\x41" "E_GOHOIPIXHYJ[ RINJOJXIYJZKYJX RGOIMKOKXLYJ[ RKONNPMSOSXTYR[ RPNRORXQYRZSYRX RNNQPQXPYR[ RSOVNXM[O[X\\YZ[ RXNZOZXYYZZ[YZX RVNYPYXXYZ[";
const char glyph110[] PROGMEM = "\x2b" "I[KOLOMPMXLYN[ RMNNONXMYNZOYNX RKOMMOOOXPYN[ ROORNTMWOWXXYV[ RTNVOVXUYVZWYVX RRNUPUXTYV[";
const char glyph111[] PROGMEM = "\x1b" "JZMPMXP[UYWX RNPNXPZ ROOOWRZ RMPOOTMWPWX RTNVPVX RRNUQUY";
const char glyph112[] PROGMEM = "\x2e" "IZLMMOMXKYMYM_LbN` RNON` RLMNNOOOXQYRZ RNYOYQZ ROZP[UYWX ROZO_PbN` ROORNTMWPWX RTNVPVX RRNUQUY";
const char glyph113[] PROGMEM = "\x1e" "J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW_XbV` RTNVPV` RRNUQU_TbV`";
const char glyph114[] PROGMEM = "\x1e" "KXMONOOPOXNYP[ RONPOPXOYPZQYPX RMOOMQOQXRYP[ RQOUMWOUPSN RTNVO";
const char glyph115[] PROGMEM = "\x28" "JZMPMSOUURWTWX RNPNSOT ROOOSPT RUSVTVX RTSUTUY RMPSMVNTOQN RRNUN RWXQ[MYOXSZ ROYQZ";
const char glyph116[] PROGMEM = "\x1a" "MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[ RNMQM RSMVM";
const char glyph117[] PROGMEM = "\x27" "I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPWXXYYY RVPWOVNUOVPVYWZ RVMTOUPUYW[YY";
const char glyph118[] PROGMEM = "\x23" "I[LMMOMXQ[SYWW RMNNONXQZ RLMNNOOOWRYSY RVMXOWPWW RVPWOVNUOVPVW RVMTOUPUX";
const char glyph119[] PROGMEM = "\x3a" "E_HMIOIXM[OYQX RINJOJXMZ RHMJNKOKWNYOY RRMPOQPQXU[WY[W RRPSORNQORPRXUZ RRMTOSPSWVYWY RZM\\O[P[W RZP[OZNYOZPZW RZMXOYPYX";
const char glyph120[] PROGMEM = "\x26" "I[LONPUZV[XY RMNOOUYWZ RLONMONVXXY RXMVMVOXOXMVOSS RQUNYL[N[NYLYL[ RNTQT RSTVT";
const char glyph121[] PROGMEM = "\x30" "I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPW]V_U`SaQaO`MaObQa RVPWOVNUOVPV^U_ RPaNa RVMTOUPU^T`Sa";
const char glyph122[] PROGMEM = "\x2a" "L[RNOPOORNTMWOWSRU RTNVOVS RRNUPUSTT RRUWWW]V_U`SaQaO`MaObQa RVWV^U_ RPaNa RTVUWU^T`Sa";
const char glyph123[] PROGMEM = "\x27" "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
const char glyph124[] PROGMEM = "\x02" "NVRBRb";
const char glyph125[] PROGMEM = "\x27" "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
const char glyph126[] PROGMEM = "\x17" "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
const char glyph127[] PROGMEM = "\x1d" "KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF";

const char *const font[96] PROGMEM =
{
	glyph032, glyph033, glyph034, glyph035, glyph036, glyph037, glyph038, glyph039, 
	glyph040, glyph041, glyph042, glyph043, glyph044, glyph045, glyph046, glyph047, 
	glyph048, glyph049, glyph050, glyph051, glyph052, glyph053, glyph054, glyph055, 
	glyph056, glyph057, glyph058, glyph059, glyph060, glyph061, glyph062, glyph063, 
	glyph064, glyph065, glyph066, glyph067, glyph068, glyph069, glyph070, glyph071, 
	glyph072, glyph073, glyph074, glyph075, glyph076, glyph077, glyph078, glyph079, 
	glyph080, glyph081, glyph082, glyph083, glyph084, glyph085, glyph086, glyph087, 
	glyph088, glyph089, glyph090, glyph091, glyph092, glyph093, glyph094, glyph095, 
	glyph096, glyph097, glyph098, glyph099, glyph100, glyph101, glyph102, glyph103, 
	glyph104, glyph105, glyph106, glyph107, glyph108, glyph109, glyph110, glyph111, 
	glyph112, glyph113, glyph114, glyph115, glyph116, glyph117, glyph118, glyph119, 
	glyph120, glyph121, glyph122, glyph123, glyph124, glyph125, glyph126, glyph127
	
};

#define FONT_INCLUDED
