//
// Hershey Font: japanese 
//
// USE RESTRICTION:
//    This distribution of the Hershey Fonts may be used by anyone for
//    any purpose, commercial or otherwise, providing that:
//
//        1. The following acknowledgements must be distributed with the font data:
//
//            - The Hershey Fonts were originally created by Dr.
//                A. V. Hershey while working at the U. S. National Bureau of Standards.
//            - The format of the Font data in this distribution was originally created by
//                James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821,
//               (mit-eddie!ci-dandelion!hurt)
//
//        2. The font data in this distribution may be converted into
//            any other format *EXCEPT* the format distributed by
//            the U.S. NTIS (which organization holds the rights
//            to the distribution and use of the font data in that
//            particular format). Not that anybody would really
//            *want* to use their format... each point is described
//            in eight bytes as "xxx yyy:", where xxx and yyy are
//            the coordinate values as ASCII numbers.
//

const char glyph032[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph033[] PROGMEM = "\x07" "D_H[GZHYIZI\\H^G_";
const char glyph034[] PROGMEM = "\x07" "D_HOJQZP\\Q RIP\\Q";
const char glyph035[] PROGMEM = "\x1a" "D_MHKGK\\ RLHL\\ RLZXZ RLHXH RWHXGZHYJ RXHX\\ RYHY\\ RLQXQ";
const char glyph036[] PROGMEM = "\x27" "D_KGIFI[ RJGJ[ RJGYG RXGYF[GZI RYGYWXYWZ RYXYYXZ RZGZYY[X[WZUY RQGQP RRGRP RJPYP";
const char glyph037[] PROGMEM = "\x2e" "D_LFJKGQ RLFMGLIINGQ RLI\\IZGXI RXI[H RRIR\\ RSIS\\ RNOLNLU RMOMU RMO[OYMWO RWOZN RGU]U[SYU RYU\\T";
const char glyph038[] PROGMEM = "\x2d" "D_QFQLPQNULXJZG\\ RRGRK RQFSGRNQROVLYI[G\\ RGM]M[KYM RYM\\L RSMTQUTVVXY[\\][ RYY[[ RSMTPVTXWZY][";
const char glyph039[] PROGMEM = "\x32" "D_JGHFH\\ RIGI\\ RIG[G RZG[F]G\\I R[G[\\ R\\G\\\\ RKKYKXJWK RQKQW RRKRW RLQXQWPVQ RKWYWXVWW RTSUUVUVTTS RI[[[";
const char glyph040[] PROGMEM = "\x26" "D_QFQLPQNULXJZG\\ RRGRK RQFSGRNQROVLYI[G\\ RSGSKTQUTVVXY[\\][ RYY[[ RSKTPVTXWZY][";
const char glyph041[] PROGMEM = "\x3c" "D_RGSFQFQ\\ RRGR\\ RGH]H[GZH RLLJKJU RKLKU RKLXL RWLXKZLYN RXLXU RYLYU RKPXP RKTXT RQTNWKYG[ RQVNXLYG[ RRTUXXZ[[]Z RRTUWYY]Z";
const char glyph042[] PROGMEM = "\x1f" "D_RHSGQFQ] RRGR] RJLHKHV RILIV RILZL RYLZK\\L[N RZLZV R[L[V RIUZU";
const char glyph043[] PROGMEM = "\x2f" "D_RHSGQFQ\\ RRGR\\ RGL]L[JYL RYL\\K RPLMRJVGY RQMOQMTKVGY RSMTPURXV[Y]X RYV[X RSMTOWSZV]X RMWVWUVTW";
const char glyph044[] PROGMEM = "\x44" "D_RGRFSEQEQG RGG]G[EYG RYG\\F RLKJJJR RKKKR RKKXK RWKXJZKYM RXKXR RYKYR RKQXQ RQQQXPZO[ RQYQZP[ RRQRZQ\\P\\O[MZ RLTGY RLTMUGY RVTXVZY[Y[XZWVT";
const char glyph045[] PROGMEM = "\x28" "D_QFQ[ RQFRFR[ RJHJP RJHKHKP RKOXO RXHXP RXHYHYP RHSH\\ RHSISI\\ RI[Z[ RZSZ\\ RZS[S[\\";
const char glyph046[] PROGMEM = "\x40" "D_HFHW RHFIGIW RIGMG RMGMV RLGMFNGNV RINMN RIUMU RUGVFTFTN RUGUN RPJ[JYIXJ RNN]N[MZN RWNWZV[ RXNXZW\\V[TZ RNR]R[QZR RQTRUSWTWTVSUQT";
const char glyph047[] PROGMEM = "\x17" "D_RHSGQFQ[ RRGR[ RRP[PYNWP RWPZO RG[][[YY[ RY[\\Z";
const char glyph048[] PROGMEM = "\x3a" "D_QGRFPFPM RQGQM RIIUITHSI RGM]M[LZM RXGUKRNNQIT RXGYHTMPPMRITGU ROQMPM\\ RNQN\\ RNQXQ RWQXPZQYS RXQX\\ RYQY\\ RNVXV RN[X[";
const char glyph049[] PROGMEM = "\x0f" "D_RHSGQFQ\\ RRGR\\ RGO]O[MYO RYO\\N";
const char glyph050[] PROGMEM = "\x07" "D_GQ]QZOXQ RXQ[P";
const char glyph051[] PROGMEM = "\x0f" "D_JJZJXHVJ RVJYI RGX]X[VYX RYX\\W";
const char glyph052[] PROGMEM = "\x17" "D_II[IYGWI RWIZH RKQYQWOUQ RUQXP RGZ]Z[XYZ RYZ\\Y";
const char glyph053[] PROGMEM = "\x30" "D_JIHHHZ RIIIZ RII[I RZI[H]I\\K R[I[Z R\\I\\Z ROIONNRMT RPIPNOQMTKV RSISSTTXTYSXR RTITRUSWSXRXP RIY[Y";
const char glyph054[] PROGMEM = "\x24" "D_IHZHXFVH RVHYG RQHNZ RRHOZ RIPVP RUPVOXPWR RVPUZ RWPWRVZ RGZ]Z[XYZ RYZ\\Y";
const char glyph055[] PROGMEM = "\x2a" "D_RISHQGQM RRHRM RGM]M[KYM RYM\\L RMQLTJXH[ RNRMT RMQORMUJYH[ RTQVSYWZY[Z\\Y[WXTTQ RYV[Y";
const char glyph056[] PROGMEM = "\x1d" "D_MINHLGLZM[Y[ZZYX RXZYZYY RMHMYNZWZYXZU RHQNPSO[MXLWN RWNYM";
const char glyph057[] PROGMEM = "\x2a" "D_RLQOOTMWJZG\\ RRLSMRPPTNWLYI[G\\ RLGUG RRGSFUGSI RSGSLTQUTVVXY[\\][ RYY[[ RSLTPVTXWZY][";
const char glyph058[] PROGMEM = "\x27" "D_NIOHMGMRLVJYG\\ RNHNRMVKYG\\ RGNTM RSMTLVMUO RTMTZU[\\[]Z\\X R[Z\\Z\\Y RUMUYVZZZ\\X]U";
const char glyph059[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph060[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph061[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph062[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph063[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph064[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph065[] PROGMEM = "\x3a" "D_OFQGQIPL RPGPRQV RKKMLRLUKXJ RUKVJXJ RSSTOUPSSPWNYLZJZIYIVJTLRNQQPVPYQ[S\\U\\W[YY[V\\T\\ RKZJYJVKTMRQP RVPXQZS[U[WZYX[V\\";
const char glyph066[] PROGMEM = "\x21" "D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\\S\\UZTWU R[P[SZT";
const char glyph067[] PROGMEM = "\x26" "D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\\ RTLVMWOWRVUUWSYP[";
const char glyph068[] PROGMEM = "\x2c" "D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZHYLVNURUSVTZU[\\[ RW[ZZ[Z\\[";
const char glyph069[] PROGMEM = "\x3d" "D_MFOGOINM RNGN[ RNTOZN[MYKXHW RHMJNNNQMSL RNNPMQLSL RHXLUQRTQVQYRZTZVYXWYUYSXRV RHXHWLU RVQXRYTYVXXWY RWKYK[L\\MZMYN RYKZLZM";
const char glyph070[] PROGMEM = "\x35" "D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX RHNJNMM RRLTNTRSVRXPZ RWMYN[P\\R\\T[SYT RZO[Q[S";
const char glyph071[] PROGMEM = "\x2d" "D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWWUVRUNULVKWKYLZN[Q\\W\\ RN[V[W\\";
const char glyph072[] PROGMEM = "\x11" "D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[";
const char glyph073[] PROGMEM = "\x2c" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\\L RIUJWKX RVMZL[K\\L RVFXGXUWXUZR\\ RWGXJ RXRWVUYR\\";
const char glyph074[] PROGMEM = "\x16" "D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY";
const char glyph075[] PROGMEM = "\x30" "D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXTVSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[";
const char glyph076[] PROGMEM = "\x10" "D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V";
const char glyph077[] PROGMEM = "\x23" "D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\\ RSGTL RTVSYQ\\ RHJJLMLVKZJ\\K RIKML RVK\\K";
const char glyph078[] PROGMEM = "\x2c" "D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHNJPLPPOUNYM[M\\N RIOPO RUN\\N";
const char glyph079[] PROGMEM = "\x2e" "D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ";
const char glyph080[] PROGMEM = "\x2f" "D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[OYOWP RXNYO RRVSXTYVZ[Z RSXUY\\Y[Z";
const char glyph081[] PROGMEM = "\x2b" "D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S[VZXWZS[O[ RXPYQZSZVYXWZ";
const char glyph082[] PROGMEM = "\x19" "D_HLJNOLSKWKZL[M\\O\\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV";
const char glyph083[] PROGMEM = "\x22" "D_HIJKLKPJUIYH[H\\I RIJPJ RUI\\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTYXZZZ[[";
const char glyph084[] PROGMEM = "\x1c" "D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[";
const char glyph085[] PROGMEM = "\x3e" "D_MFOGOIMOLRJWH[ RNGNJMO RLRJVHYH[ RHMJNLNOMQLSK RQLRJSK RVJXJZK\\MZLXM RXJZL RVOVQWTXVXXWZU[R[PZOXPVRUUUWV[Z RVQWVWYU[ RYXZZ[Z";
const char glyph086[] PROGMEM = "\x29" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RSJVIYI[JYJWK RWIYJ RQSQURWUX\\X RQURVUWZW\\X";
const char glyph087[] PROGMEM = "\x44" "D_JILJLO RKJLOMRNTOVPW RNTPVPW RRGTHTJROOVMYKZIZHXHVISJQLOOMSLVLYM[O\\R\\U[XZYXZVZTYSXSWTVVUXUZV\\Y RSHSJRO RJZIXIUJRLO RVLXMZO[R[VZY RZV\\X\\Y";
const char glyph088[] PROGMEM = "\x3b" "D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMNLMP ROMMPKSHWHVKSOOSLVKXKZL[N[UZXYYWZUZSYRXRWSVUUWUYVZW\\Z RXKYLZNZVYY RZW\\Y\\Z";
const char glyph089[] PROGMEM = "\x29" "D_QHRJRMQPPRNULWJWIVHTHQINKKNIQHTHWIYJ[L\\O\\R[UYWWXTYQY RNULVJVITIQJMKK RWIZL[O[RZUWX";
const char glyph090[] PROGMEM = "\x32" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L";
const char glyph091[] PROGMEM = "\x33" "D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS";
const char glyph092[] PROGMEM = "\x34" "D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X";
const char glyph093[] PROGMEM = "\x10" "D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV";
const char glyph094[] PROGMEM = "\x3c" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y";
const char glyph095[] PROGMEM = "\x2c" "D_RFTGTXSZQ[O[MZLXMVOUQUTVWXZ[ RSGTK RWXZZZ[ RHIJKSKZJ RIJNK RSKWJYIZJ RMPOQSQWPYO RWPXNYO";
const char glyph096[] PROGMEM = "\x2b" "D_JGKIMIPHSFTG RKHPH RTGPMMSKVJWIWHVHTIRKQPQTRWS\\U RSFPM RTR\\T\\U RVMXNXTWWUYSZP[ RWNWUVX";
const char glyph097[] PROGMEM = "\x38" "D_MFOGOINMMQLTKVJWIWHVHTIRJQKQLRLWMZO[U[XZYYXXWVVRVNWMYM[N\\P\\Q[QYR RNGNM RLWMYOZUZWYXX RYM[O[Q RHKKLNLQKSJ RQKRISJ";
const char glyph098[] PROGMEM = "\x3c" "D_JILJLO RKJLOMRNTOVPW RNTPVPW RSGUHUJTMRRQTOWMYKZIZHYHWITJRLPONRMVMYN[P\\S\\V[XZYXZU[R[ RTHTJRR RJZIYIVJSLP RVMXNZP[S[VZXXZ";
const char glyph099[] PROGMEM = "\x29" "D_OFQGQIPM RPGPTQXRZT[X[ZZ[X[VZTXRUP RW[YZZXZUYS RLJMKPLSL RMKRKSL RSLPMNNLPKRLTNUSU";
const char glyph100[] PROGMEM = "\x2f" "D_PFRGSHTJSKPJMJLKLMOTQ[ RRGSISK ROTRZQ[ RHNIPKPNNRLVKYK[L\\N\\P[RZSWTTTQS RIOKONN RYKZL[N[PZRYSWT";
const char glyph101[] PROGMEM = "\x21" "D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\\S\\UZTWU R[P[SZT";
const char glyph102[] PROGMEM = "\x33" "D_HJJKJMIP RIKITJWKXKVLSMQONRKUJXJZK[L\\N\\Q[SYUWVTVRUPSOPOMPIQGSFUFVHVSUWTYQ[ RITJVKV RZK[N[QZT RVSUVTXQ[";
const char glyph103[] PROGMEM = "\x2c" "D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZHYLVNURUSVTZU[\\[ RW[ZZ[Z\\[";
const char glyph104[] PROGMEM = "\x21" "D_PFSGSIRN RRGRXQZO[L[JZIYIWJVLUOURVVX[[ RRVWX[Z[[ RRNUNYM RUNWMXLYM";
const char glyph105[] PROGMEM = "\x29" "D_OFQFSGTHRHPI RQFRGRH RLLKNJRJTKUORQQTPWPYQZSZUYWWYUZQ[O[ RJRKTLT RWPXQYSYUXWVYTZQ[";
const char glyph106[] PROGMEM = "\x24" "D_LFNGNILM RMGMILMLPMSNTNROOQLSJUIWIXJYMYRXVVYS[O\\ RLPMRNR RVIWJXMXRWVUYS[";
const char glyph107[] PROGMEM = "\x31" "D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZWYYXZV[S[QZPYPXQWSWUXWZ RVPXRYTYWXYV[";
const char glyph108[] PROGMEM = "\x30" "D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSOOSLVKWKYLZNYXYZZ[ RWKXLYNXXXZY[Z[[Z\\X";
const char glyph109[] PROGMEM = "\x29" "D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZWYYW[T\\R\\ RVPXRYTYWXZ";
const char glyph110[] PROGMEM = "\x30" "D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSNPQNTMWMYNZO[Q[TZWXYVZS[ RWMYOZQZTYWVZ";
const char glyph111[] PROGMEM = "\x33" "D_MGNIPITG RNHPHTGUH RUHQNMVLXKYIYHWHUISKQNORNVNYO[Q\\S\\V[XYZW[T[RZQYQXRWTWVXXZ RTGQN RJYIWIUJR RZP[S[VZY";
const char glyph112[] PROGMEM = "\x26" "D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\\ RTLVMWOWRVUUWSYP[";
const char glyph113[] PROGMEM = "\x44" "D_LGMIOIQHTF RMHOHRGTFUG RUGQJMNJR RTFQJ RJRJPMNOMRLULWMXOXQWSUTPTOSOQPPRPSQSSRTNUKWHZH[I[KW RJYLXNXPZQZSXVWYW[X\\Y\\[[ZYZ RNXPYQYSX RYW[Y[Z";
const char glyph114[] PROGMEM = "\x38" "D_PFRGRHPLNOKRHU RQGQHPL RKRHTHU RMPOOQOSPTRTV RQORPSRSWTV RIJLKOKSJWI RSJVHWI R[O\\QTRQSOTNVNXOZQ[Y[ R[PTR RT[XZY[";
const char glyph115[] PROGMEM = "\x1d" "D_QFSHPMLTH[ RRGPM RH[HYLTNRPQRQTRTWUYVZ RRQSRSWTYVZXZZY[W\\T";
const char glyph116[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph117[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph118[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph119[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph120[] PROGMEM = "\x3b" "D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX RHNJNMM RRLTNTRSVRXPZ RWMYN[P\\R\\T[SYT RZO[Q[S RWHYJ RYF[H";
const char glyph121[] PROGMEM = "\x33" "D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWWUVRUNULVKWKYLZN[Q\\W\\ RN[V[W\\ RWHYJ RYF[H";
const char glyph122[] PROGMEM = "\x17" "D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[ RYH[J R[F]H";
const char glyph123[] PROGMEM = "\x32" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\\L RIUJWKX RVMZL[K\\L RVFXGXUWXUZR\\ RWGXJ RXRWVUYR\\ R[G]I R]E_G";
const char glyph124[] PROGMEM = "\x1c" "D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY RYG[I R[E]G";
const char glyph125[] PROGMEM = "\x36" "D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXTVSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[ RZG\\I R\\E^G";
const char glyph126[] PROGMEM = "\x16" "D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V RSHUJ RUFWH";
const char glyph127[] PROGMEM = "\x29" "D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\\ RSGTL RTVSYQ\\ RHJJLMLVKZJ\\K RIKML RVK\\K RXFZH R[E]G";
const char glyph128[] PROGMEM = "\x32" "D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHNJPLPPOUNYM[M\\N RIOPO RUN\\N RZH\\J R\\F^H";
const char glyph129[] PROGMEM = "\x34" "D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ RZH\\J R\\F^H";
const char glyph130[] PROGMEM = "\x35" "D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[OYOWP RXNYO RRVSXTYVZ[Z RSXUY\\Y[Z RXHZJ RZF\\H";
const char glyph131[] PROGMEM = "\x31" "D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S[VZXWZS[O[ RXPYQZSZVYXWZ RXIZK RZG\\I";
const char glyph132[] PROGMEM = "\x1f" "D_HLJNOLSKWKZL[M\\O\\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV RZH\\J R\\F^H";
const char glyph133[] PROGMEM = "\x28" "D_HIJKLKPJUIYH[H\\I RIJPJ RUI\\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTYXZZZ[[ RZM\\O R\\K^M";
const char glyph134[] PROGMEM = "\x22" "D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[ RXIZK RZG\\I";
const char glyph135[] PROGMEM = "\x38" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L RZG\\I R\\E^G";
const char glyph136[] PROGMEM = "\x39" "D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS RYH[J R[F]H";
const char glyph137[] PROGMEM = "\x3a" "D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X RWIYK RYG[I";
const char glyph138[] PROGMEM = "\x16" "D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV RUJWL RWHYJ";
const char glyph139[] PROGMEM = "\x42" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R[I]K R]G_I";
const char glyph140[] PROGMEM = "\x3c" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTTVU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L R[EZFZH[I]I^H^F]E[E";
const char glyph141[] PROGMEM = "\x3d" "D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLYOYRXTVUTVQ RVIXLYN[Q\\SZSYT RUIXL RYNZQZS RZFYGYIZJ\\J]I]G\\FZF";
const char glyph142[] PROGMEM = "\x3e" "D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSYRZ RIYLVOTRS RVSYT[V\\XYX RIYIXLV RVSXTZV[X RXGWHWJXKZK[J[HZGXG";
const char glyph143[] PROGMEM = "\x1a" "D_HPJRMM RIQNLPLUQYT[U\\VZVXW RUQZV RVHUIUKVLXLYKYIXHVH";
const char glyph144[] PROGMEM = "\x46" "D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPOSPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R\\G[H[J\\K^K_J_H^G\\G";
const char glyph145[] PROGMEM = "\x23" "D_HGJIOHUGZF\\H RIHOH RUG[G R\\HZJVMTN R[GYJWLTN RRMTNTQSUQXN[ RRMSNSQRUPY";
const char glyph146[] PROGMEM = "\x15" "D_VFXHULRONRKT RWGVISMOQKT RSNUOU\\ RSNTOT[U\\";
const char glyph147[] PROGMEM = "\x29" "D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUURXOZM[ RYKXNVRSVPYM[";
const char glyph148[] PROGMEM = "\x16" "D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\\W RIW\\W";
const char glyph149[] PROGMEM = "\x22" "D_RFUGUYT[SYPW RTGTXSY RHLJNOMULZK\\L RIMOM RUL\\L RSMPQLUHX RTMRPOSKVHX";
const char glyph150[] PROGMEM = "\x28" "D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWYU[TZRY RYLXSWWVYTZ";
const char glyph151[] PROGMEM = "\x21" "D_OFRGT[ RQGS\\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\\R RISOS RUR\\R";
const char glyph152[] PROGMEM = "\x21" "D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\";
const char glyph153[] PROGMEM = "\x1f" "D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\\N RTN\\N RROTQRUPXNZL\\ RSPRSPWNZ";
const char glyph154[] PROGMEM = "\x17" "D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW";
const char glyph155[] PROGMEM = "\x23" "D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\\M RINON RUM\\M";
const char glyph156[] PROGMEM = "\x1b" "D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L";
const char glyph157[] PROGMEM = "\x1d" "D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS";
const char glyph158[] PROGMEM = "\x22" "D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\\O RIOOO RUN[N R\\OYQVT R[NVT";
const char glyph159[] PROGMEM = "\x16" "D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ";
const char glyph160[] PROGMEM = "\x2b" "D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RNPQQSRVTWUWVVVUTSR";
const char glyph161[] PROGMEM = "\x23" "D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N";
const char glyph162[] PROGMEM = "\x1e" "D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ";
const char glyph163[] PROGMEM = "\x1f" "D_LFNHWFXG RMGXG RHNJPOOUNZM\\N RIOOO RUN\\N RSOSQRUPXM[ RRORQQUOY";
const char glyph164[] PROGMEM = "\x10" "D_MFPGP\\ ROGO[P\\ RPOROUPVQVRURTPRO";
const char glyph165[] PROGMEM = "\x1b" "D_QFTGTLSQRTQVOYM[ RSGSLRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N";
const char glyph166[] PROGMEM = "\x0f" "D_LJNLWJXK RMKXK RHVJXZV\\W RIW\\W";
const char glyph167[] PROGMEM = "\x1f" "D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RMOPPTRWTYVYWXWVTTR";
const char glyph168[] PROGMEM = "\x2b" "D_PFRGSHSIRIQGPF RJLLNVLXN RKMWM RXNTRQTOUJW RWMUPSRPTJW RRSSTS\\ RRSR[S\\ RXUZV[W[XZXYVXU";
const char glyph169[] PROGMEM = "\x0e" "D_WHYJVPSTPWMYKZ RXIWLTQQUNXKZ";
const char glyph170[] PROGMEM = "\x13" "D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN";
const char glyph171[] PROGMEM = "\x18" "D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN";
const char glyph172[] PROGMEM = "\x18" "D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY";
const char glyph173[] PROGMEM = "\x0e" "D_GQISPLQL[V RHRJQNN RUPZT\\U[V";
const char glyph174[] PROGMEM = "\x27" "D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS";
const char glyph175[] PROGMEM = "\x1e" "D_HLJNOMULZK\\M RIMOM RUL[L R\\MZOVRTS R[LYOWQTS RQRTTVVVWUWTUQR";
const char glyph176[] PROGMEM = "\x1b" "D_PFSGUHVIVJUJSHPF RMMPNROSPSQRQPOMM RNVSXUYVZV[U[SYPWNV";
const char glyph177[] PROGMEM = "\x15" "D_RITKMW RSJMW RHWJYYV RIXYV RVSXUZX[X[WYUVS";
const char glyph178[] PROGMEM = "\x18" "D_WHYJVPSTPWMYKZ RXIWLUPRTOWKZ RONSPVRXTXUWUVSTQQO";
const char glyph179[] PROGMEM = "\x22" "D_LINKWIXJ RMJXJ RQKQVRXTY[Y RRKRMQS RVYZX[Y RHQJSORUQZP\\Q RIROR RUQ\\Q";
const char glyph180[] PROGMEM = "\x1e" "D_OFRGT[ RQGS\\T[ RHLJNOMULZK\\M RIMOM RUL[L R\\MYPVRTS R[LZNWQTS";
const char glyph181[] PROGMEM = "\x15" "D_VFXHULRONRKT RWGVISMOQKT RSNUOU\\ RSNTOT[U\\";
const char glyph182[] PROGMEM = "\x17" "D_IJKLUJWL RJKVK RWLVOUV RVKUPUV RHVJXZV\\W RIW\\W";
const char glyph183[] PROGMEM = "\x16" "D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\\W RIW\\W";
const char glyph184[] PROGMEM = "\x1d" "D_JJLLXJZL RKKYK RJPLRXP RKQXQ RJVLXXV RKWXW RZLYOYY RYKXPXY";
const char glyph185[] PROGMEM = "\x1d" "D_LFNHWFXG RMGXG RJMLOWMYO RKNXN RYOWRTUQWOXLY RXNWPUSSUPWLY";
const char glyph186[] PROGMEM = "\x14" "D_LINJNOMS RMJMS RTFWGWQVUTXQ[ RVGVQUUTWQ[";
const char glyph187[] PROGMEM = "\x1e" "D_LJNKNNMRKUHX RMKMNLRKTHX RQISJSMRS RRJRVSXUXWWYU\\Q RRVSWVWXV";
const char glyph188[] PROGMEM = "\x14" "D_HIKJKMJS RJJJVKXNXQWTUXR[O RJVKWNWQVUTXR";
const char glyph189[] PROGMEM = "\x1d" "D_JJLLXJZL RKKYK RKKKZ RLLLXKZ RZLYOXV RYKXPXV RLXXVYW RLWYW";
const char glyph190[] PROGMEM = "\x20" "D_JGKIKNLO RLILO RLIYI RJGKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY";
const char glyph191[] PROGMEM = "\x1e" "D_QFTGT[ RSGS\\T[ RJJLLXJZK RKKZK RLLNMNR RMMMR RHQJSZQ\\R RIR\\R";
const char glyph192[] PROGMEM = "\x29" "D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUURXOZM[ RYKXNVRSVPYM[";
const char glyph193[] PROGMEM = "\x1d" "D_JJLLXJZL RKKYK RZLWNSQ RYKSQ RQPSQSW RRQRW RHVJXZV\\W RIW\\W";
const char glyph194[] PROGMEM = "\x1f" "D_JGLIYI RKHOI RUIXHZJ RLNNPVO RMOVO RZJWPUSRVOXMY RYIXLVPSTPWMY";
const char glyph195[] PROGMEM = "\x13" "D_JHLIMJMKLKKIJH RIWKYOWSTWP[K RJXOVSS[K";
const char glyph196[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph197[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph198[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph199[] PROGMEM = "\x05" "D_HYGZH[IZHY";
const char glyph200[] PROGMEM = "\x2e" "D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWYU[TZRY RYLXSWWVYTZ RZH\\J R\\F^H";
const char glyph201[] PROGMEM = "\x27" "D_OFRGT[ RQGS\\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\\R RISOS RUR\\R RZH\\J R\\F^H";
const char glyph202[] PROGMEM = "\x27" "D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RYH[J R[F]H";
const char glyph203[] PROGMEM = "\x25" "D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\\N RTN\\N RROTQRUPXNZL\\ RSPRSPWNZ RYH[J R[F]H";
const char glyph204[] PROGMEM = "\x1d" "D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW RZH\\J R\\F^H";
const char glyph205[] PROGMEM = "\x29" "D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\\M RINON RUM\\M RZH\\J R\\F^H";
const char glyph206[] PROGMEM = "\x21" "D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L RVHXJ RXFZH";
const char glyph207[] PROGMEM = "\x23" "D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS RZH\\J R\\F^H";
const char glyph208[] PROGMEM = "\x28" "D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\\O RIOOO RUN[N R\\OYQVT R[NVT RYH[J R[F]H";
const char glyph209[] PROGMEM = "\x1c" "D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R[G]I R]E_G";
const char glyph210[] PROGMEM = "\x31" "D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\\ RXKWNURRVOYK\\ RNPQQSRVTWUWVVVUTSR RYH[J R[F]H";
const char glyph211[] PROGMEM = "\x29" "D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\\N RIOOO RUN\\N RZH\\J R\\F^H";
const char glyph212[] PROGMEM = "\x24" "D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R[G]I R]E_G";
const char glyph213[] PROGMEM = "\x25" "D_LFNHWFXG RMGXG RHNJPOOUNZM\\N RIOOO RUN\\N RSOSQRUPXM[ RRORQQUOY RZH\\J R\\F^H";
const char glyph214[] PROGMEM = "\x16" "D_MFPGP\\ ROGO[P\\ RPOROUPVQVRURTPRO RTHVJ RVFXH";
const char glyph215[] PROGMEM = "\x19" "D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN RYI[K R[G]I";
const char glyph216[] PROGMEM = "\x1e" "D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RYI[K R[G]I";
const char glyph217[] PROGMEM = "\x1e" "D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R[G]I R]E_G";
const char glyph218[] PROGMEM = "\x14" "D_GQISPLQL[V RHRJQNN RUPZT\\U[V RVJXL RXHZJ";
const char glyph219[] PROGMEM = "\x2d" "D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS RZG\\I R\\E^G";
const char glyph220[] PROGMEM = "\x1d" "D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\\U\\V[VZRXN RZGYHYJZK\\K]J]H\\GZG";
const char glyph221[] PROGMEM = "\x22" "D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RZGYHYJZK\\K]J]H\\GZG";
const char glyph222[] PROGMEM = "\x22" "D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R\\E[F[H\\I^I_H_F^E\\E";
const char glyph223[] PROGMEM = "\x18" "D_GQISPLQL[V RHRJQNN RUPZT\\U[V RWHVIVKWLYLZKZIYHWH";
const char glyph224[] PROGMEM = "\x31" "D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\\L RIMOM RUL\\L RLSJVIWHWHVJULS RXS[U\\V\\W[WZUXS R[EZFZH[I]I^H^F]E[E";

const char *const font[193] PROGMEM =
{
	glyph032, glyph033, glyph034, glyph035, glyph036, glyph037, glyph038, glyph039, 
	glyph040, glyph041, glyph042, glyph043, glyph044, glyph045, glyph046, glyph047, 
	glyph048, glyph049, glyph050, glyph051, glyph052, glyph053, glyph054, glyph055, 
	glyph056, glyph057, glyph058, glyph059, glyph060, glyph061, glyph062, glyph063, 
	glyph064, glyph065, glyph066, glyph067, glyph068, glyph069, glyph070, glyph071, 
	glyph072, glyph073, glyph074, glyph075, glyph076, glyph077, glyph078, glyph079, 
	glyph080, glyph081, glyph082, glyph083, glyph084, glyph085, glyph086, glyph087, 
	glyph088, glyph089, glyph090, glyph091, glyph092, glyph093, glyph094, glyph095, 
	glyph096, glyph097, glyph098, glyph099, glyph100, glyph101, glyph102, glyph103, 
	glyph104, glyph105, glyph106, glyph107, glyph108, glyph109, glyph110, glyph111, 
	glyph112, glyph113, glyph114, glyph115, glyph116, glyph117, glyph118, glyph119, 
	glyph120, glyph121, glyph122, glyph123, glyph124, glyph125, glyph126, glyph127, 
	glyph128, glyph129, glyph130, glyph131, glyph132, glyph133, glyph134, glyph135, 
	glyph136, glyph137, glyph138, glyph139, glyph140, glyph141, glyph142, glyph143, 
	glyph144, glyph145, glyph146, glyph147, glyph148, glyph149, glyph150, glyph151, 
	glyph152, glyph153, glyph154, glyph155, glyph156, glyph157, glyph158, glyph159, 
	glyph160, glyph161, glyph162, glyph163, glyph164, glyph165, glyph166, glyph167, 
	glyph168, glyph169, glyph170, glyph171, glyph172, glyph173, glyph174, glyph175, 
	glyph176, glyph177, glyph178, glyph179, glyph180, glyph181, glyph182, glyph183, 
	glyph184, glyph185, glyph186, glyph187, glyph188, glyph189, glyph190, glyph191, 
	glyph192, glyph193, glyph194, glyph195, glyph196, glyph197, glyph198, glyph199, 
	glyph200, glyph201, glyph202, glyph203, glyph204, glyph205, glyph206, glyph207, 
	glyph208, glyph209, glyph210, glyph211, glyph212, glyph213, glyph214, glyph215, 
	glyph216, glyph217, glyph218, glyph219, glyph220, glyph221, glyph222, glyph223, 
	glyph224
};
