//
// Hershey Font: music 
//
// USE RESTRICTION:
//    This distribution of the Hershey Fonts may be used by anyone for
//    any purpose, commercial or otherwise, providing that:
//
//        1. The following acknowledgements must be distributed with the font data:
//
//            - The Hershey Fonts were originally created by Dr.
//                A. V. Hershey while working at the U. S. National Bureau of Standards.
//            - The format of the Font data in this distribution was originally created by
//                James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821,
//               (mit-eddie!ci-dandelion!hurt)
//
//        2. The font data in this distribution may be converted into
//            any other format *EXCEPT* the format distributed by
//            the U.S. NTIS (which organization holds the rights
//            to the distribution and use of the font data in that
//            particular format). Not that anybody would really
//            *want* to use their format... each point is described
//            in eight bytes as "xxx yyy:", where xxx and yyy are
//            the coordinate values as ASCII numbers.
//

const char glyph032[] PROGMEM = "\x00" "JZ";
const char glyph033[] PROGMEM = "\x0e" "MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
const char glyph034[] PROGMEM = "\x11" "JZMPQRTTVVWYW[V]U^ RMQST RMRPSTUVWWY";
const char glyph035[] PROGMEM = "\x11" "JZWKVMTOPQMR RSPMS RUFVGWIWKVNTPQRMT";
const char glyph036[] PROGMEM = "\x23" "H\\SMONLPKRKTLVNWQWUVXTYRYPXNVMSM RXNSM RVMQNLP RONKR RLVQW RNWSVXT RUVYR";
const char glyph037[] PROGMEM = "\x23" "H\\SMONLPKRKTLVNWQWUVXTYRYPXNVMSM RXNSM RVMQNLP RONKR RLVQW RNWSVXT RUVYR";
const char glyph038[] PROGMEM = "\x21" "J[SMPNNPMRMTNVPWRWUVWTXRXPWNUMSM ROPUM RNRVN RMTWO RNUXP ROVWR RPWVT";
const char glyph039[] PROGMEM = "\x11" "JZOGO^ RUFU] RMNWL RMOWM RMWWU RMXWV";
const char glyph040[] PROGMEM = "\x11" "JZNFNX RVLV^ RNNVL RNOVM RNWVU RNXVV";
const char glyph041[] PROGMEM = "\x18" "JZNBNW RNNQLTLVMWOWQVSSUQVNW RNNQMTMVN RUMVOVQUSSU";
const char glyph042[] PROGMEM = "\x11" "E_HIHL R\\I\\L RHI\\I RHJ\\J RHK\\K RHL\\L";
const char glyph043[] PROGMEM = "\x11" "JZMNMQ RWNWQ RMNWN RMOWO RMPWP RMQWQ";
const char glyph044[] PROGMEM = "\x30" "JZMLWX RMLONQOTOVNWMWKUKUMTO RONTO RQOWM RVKVN RULWL RWXUVSUPUNVMWMYOYOWPU RUVPU RSUMW RNVNY RMXOX";
const char glyph045[] PROGMEM = "\x19" "JZPOOMOKMKMMNNPOSOUNWL RNKNN RMLOL RMMSO RPOUN RWLWY";
const char glyph046[] PROGMEM = "\x23" "JZQCVMRTRU RULQS RTITKPRRUUY RW\\UYSXQXOYN[N]O_Ra RW\\UZSYOYO]P_Ra RSXPZN]";
const char glyph047[] PROGMEM = "\x66" "EfNSOUQVSVUUVSVQUOSNQNOONPMSMVNYP[S\\V\\Y[[Y\\W]T]P\\MZJXIUHRHOIMJKLIOHSHXI]KaMcPeTfYf]e`cba RKLJNIRIXJ\\L`NbQdUeYe]d_cba RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU RaLaNcNcLaL RbLbN RaMcM RaVaXcXcVaV RbVbX RaWcW";
const char glyph048[] PROGMEM = "\x27" "H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
const char glyph049[] PROGMEM = "\x0a" "H\\NJPISFS[ RRGR[ RN[W[";
const char glyph050[] PROGMEM = "\x2c" "H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
const char glyph051[] PROGMEM = "\x2e" "H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
const char glyph052[] PROGMEM = "\x0c" "H\\THT[ RUFU[ RUFJUZU RQ[X[";
const char glyph053[] PROGMEM = "\x26" "H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
const char glyph054[] PROGMEM = "\x2f" "H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
const char glyph055[] PROGMEM = "\x1e" "H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
const char glyph056[] PROGMEM = "\x3e" "H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
const char glyph057[] PROGMEM = "\x2f" "H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
const char glyph058[] PROGMEM = "\x0b" "MWRMQNROSNRM RRYQZR[SZRY";
const char glyph059[] PROGMEM = "\x55" "A^GfHfIeIdHcGcFdFfGhIiKiNhPfQdR`RUQ;Q4R/S-U,V,X-Y/Y3X6W8U;P?JCHEFHEJDNDREVGYJ[N\\R\\V[XZZW[T[PZMYKWITHPHMIKKJNJRKUMW RGdGeHeHdGd RU;Q?LCIFGIFKENERFVGXJ[ RR\\U[WZYWZTZPYMXKVITH";
const char glyph060[] PROGMEM = "\x66" "EfNSOUQVSVUUVSVQUOSNQNOONPMSMVNYP[S\\V\\Y[[Y\\W]T]P\\MZJXIUHRHOIMJKLIOHSHXI]KaMcPeTfYf]e`cba RKLJNIRIXJ\\L`NbQdUeYe]d_cba RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU RaLaNcNcLaL RbLbN RaMcM RaVaXcXcVaV RbVbX RaWcW";
const char glyph061[] PROGMEM = "\x58" "IjNQOOQNSNUOVQVSUUSVQVOUNTMQMNNKPISHWH[I^K`NaRaW`[_]]`ZcVfQiMk RWHZI]K_N`R`W_[^]\\`YcTgQi RPOTO ROPUP RNQVQ RNRVR RNSVS ROTUT RPUTU ReLeNgNgLeL RfLfN ReMgM ReVeXgXgVeV RfVfX ReWgW";
const char glyph062[] PROGMEM = "\x1d" "D`H@Hd RM@Md RW@Wd R\\@\\d RMMWK RMNWL RMOWM RMWWU RMXWV RMYWW";
const char glyph063[] PROGMEM = "\x54" "D`H>Hf RI>If RM>Mf RQBSBSDQDQAR?T>W>Y?[A\\D\\I[LYNWOUOSNRLQNOQNROSQVRXSVUUWUYV[X\\[\\`[cYeWfTfReQcQ`S`SbQb RRBRD RQCSC RY?ZA[D[IZLYN RRLRNPQNRPSRVRX RYVZX[[[`ZcYe RR`Rb RQaSa";
const char glyph064[] PROGMEM = "\x11" "JZMNMQ RWNWQ RMNWN RMOWO RMPWP RMQWQ";
const char glyph065[] PROGMEM = "\x11" "H\\UFH[ RUFV[ RTHU[ RLUUU RF[L[ RR[X[";
const char glyph066[] PROGMEM = "\x28" "F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVP RWFYGZIZKYNXOVP RMPVPXQYSYUXXVZR[F[ RVPWQXSXUWXUZR[";
const char glyph067[] PROGMEM = "\x21" "H]ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[S[UZWXXV RTFRGPINLMOLSLVMYNZP[";
const char glyph068[] PROGMEM = "\x1d" "F]OFI[ RPFJ[ RLFUFXGYHZKZOYSWWUYSZO[F[ RUFWGXHYKYOXSVWTYRZO[";
const char glyph069[] PROGMEM = "\x15" "F]OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[U[WVT[";
const char glyph070[] PROGMEM = "\x13" "F\\OFI[ RPFJ[ RTLRT RLF[FZLZF RMPSP RF[M[";
const char glyph071[] PROGMEM = "\x29" "H^ZH[H\\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[R[UZWXYT RTFRGPINLMOLSLVMYNZP[ RR[TZVXXT RUT\\T";
const char glyph072[] PROGMEM = "\x1a" "E_NFH[ ROFI[ R[FU[ R\\FV[ RKFRF RXF_F RLPXP RE[L[ RR[Y[";
const char glyph073[] PROGMEM = "\x0b" "LYUFO[ RVFP[ RRFYF RL[S[";
const char glyph074[] PROGMEM = "\x14" "I[XFSWRYQZO[M[KZJXJVKULVKW RWFRWQYO[ RTF[F";
const char glyph075[] PROGMEM = "\x1a" "F]OFI[ RPFJ[ R]FLS RSOW[ RROV[ RLFSF RYF_F RF[M[ RS[Y[";
const char glyph076[] PROGMEM = "\x0d" "H\\QFK[ RRFL[ RNFUF RH[W[YUV[";
const char glyph077[] PROGMEM = "\x1d" "E`NFH[ RNFO[ ROFPY R\\FO[ R\\FV[ R]FW[ RKFOF R\\F`F RE[K[ RS[Z[";
const char glyph078[] PROGMEM = "\x14" "F_OFI[ ROFVX ROIV[ R\\FV[ RLFOF RYF_F RF[L[";
const char glyph079[] PROGMEM = "\x29" "G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF";
const char glyph080[] PROGMEM = "\x1a" "F]OFI[ RPFJ[ RLFXF[G\\I\\K[NYPUQMQ RXFZG[I[KZNXPUQ RF[M[";
const char glyph081[] PROGMEM = "\x3c" "G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF RSFQGOIMLLOKSKVLYN[ RQ[SZUXWUXRYNYKXHVF RLYLXMVOUPURVSXS_T`V`W^W] RSXT^U_V_W^";
const char glyph082[] PROGMEM = "\x29" "F^OFI[ RPFJ[ RLFWFZG[I[KZNYOVPMP RWFYGZIZKYNXOVP RRPTQURVZW[Y[ZYZX RURWYXZYZZY RF[M[";
const char glyph083[] PROGMEM = "\x22" "G^ZH[H\\F[L[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJUI[JYKY";
const char glyph084[] PROGMEM = "\x0f" "H]UFO[ RVFP[ ROFLLNF]F\\L\\F RL[S[";
const char glyph085[] PROGMEM = "\x18" "F_NFKQJUJXKZN[R[UZWXXU\\F ROFLQKUKXLZN[ RKFRF RYF_F";
const char glyph086[] PROGMEM = "\x0e" "H\\NFO[ ROFPY R\\FO[ RLFRF RXF^F";
const char glyph087[] PROGMEM = "\x17" "E_MFK[ RNFLY RUFK[ RUFS[ RVFTY R]FS[ RJFQF RZF`F";
const char glyph088[] PROGMEM = "\x14" "G]NFU[ ROFV[ R\\FH[ RLFRF RXF^F RF[L[ RR[X[";
const char glyph089[] PROGMEM = "\x13" "H]NFRPO[ ROFSPP[ R]FSP RLFRF RYF_F RL[S[";
const char glyph090[] PROGMEM = "\x0f" "G][FH[ R\\FI[ ROFLLNF\\F RH[V[XUU[";
const char glyph091[] PROGMEM = "\x0b" "KYOBOb RPBPb ROBVB RObVb";
const char glyph092[] PROGMEM = "\x02" "KYKFY^";
const char glyph093[] PROGMEM = "\x0b" "KYTBTb RUBUb RNBUB RNbUb";
const char glyph094[] PROGMEM = "\x06" "LXTFOL RTFUGOL";
const char glyph095[] PROGMEM = "\x02" "E_IR[R";
const char glyph096[] PROGMEM = "\x06" "LXPFUL RPFOGUL";
const char glyph097[] PROGMEM = "\x26" "H]XMVTUXUZV[Y[[Y\\W RYMWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
const char glyph098[] PROGMEM = "\x23" "H[PFLSLVMYNZ RQFMS RMSNPPNRMTMVNWOXQXTWWUZR[P[NZMWMS RVNWPWTVWTZR[ RMFQF";
const char glyph099[] PROGMEM = "\x18" "I[WPWQXQXPWNUMRMONMQLTLWMYNZP[R[UZWW RRMPNNQMTMXNZ";
const char glyph100[] PROGMEM = "\x29" "H]ZFVTUXUZV[Y[[Y\\W R[FWTVXVZW[ RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RWF[F";
const char glyph101[] PROGMEM = "\x19" "I[MVQUTTWRXPWNUMRMONMQLTLWMYNZP[R[UZWX RRMPNNQMTMXNZ";
const char glyph102[] PROGMEM = "\x22" "KZZGYHZI[H[GZFXFVGUHTJSMP[O_Na RXFVHUJTNRWQ[P^O`NaLbJbIaI`J_K`Ja ROMYM";
const char glyph103[] PROGMEM = "\x2a" "H\\YMU[T^RaObLbJaI`I_J^K_J` RXMT[S^QaOb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ";
const char glyph104[] PROGMEM = "\x1e" "H]PFJ[ RQFK[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W RMFQF";
const char glyph105[] PROGMEM = "\x19" "LYUFTGUHVGUF RMQNOPMSMTNTQRWRZS[ RRMSNSQQWQZR[U[WYXW";
const char glyph106[] PROGMEM = "\x1f" "LYVFUGVHWGVF RNQOOQMTMUNUQR[Q^P`OaMbKbJaJ`K_L`Ka RSMTNTQQ[P^O`Mb";
const char glyph107[] PROGMEM = "\x21" "H\\PFJ[ RQFK[ RXNWOXPYOYNXMWMUNQROSMS ROSQTSZT[ ROSPTRZS[U[WZYW RMFQF";
const char glyph108[] PROGMEM = "\x11" "MYUFQTPXPZQ[T[VYWW RVFRTQXQZR[ RRFVF";
const char glyph109[] PROGMEM = "\x33" "AbBQCOEMHMINIPHTF[ RGMHNHPGTE[ RHTJPLNNMPMRNSOSQP[ RPMRORQO[ RRTTPVNXMZM\\N]O]Q[W[Z\\[ RZM\\O\\QZWZZ[[^[`YaW";
const char glyph110[] PROGMEM = "\x24" "F]GQHOJMMMNNNPMTK[ RLMMNMPLTJ[ RMTOPQNSMUMWNXOXQVWVZW[ RUMWOWQUWUZV[Y[[Y\\W";
const char glyph111[] PROGMEM = "\x1f" "I[RMONMQLTLWMYNZP[R[UZWWXTXQWOVNTMRM RRMPNNQMTMXNZ RR[TZVWWTWPVN";
const char glyph112[] PROGMEM = "\x29" "G\\HQIOKMNMONOPNTJb RMMNNNPMTIb RNTOQQNSMUMWNXOYQYTXWVZS[Q[OZNWNT RWNXPXTWWUZS[ RFbMb";
const char glyph113[] PROGMEM = "\x20" "H\\XMRb RYMSb RVTVQUNSMQMNNLQKTKWLYMZO[Q[SZUWVT RQMONMQLTLXMZ RObVb";
const char glyph114[] PROGMEM = "\x19" "IZJQKOMMPMQNQPPTN[ ROMPNPPOTM[ RPTRPTNVMXMYNYOXPWOXN";
const char glyph115[] PROGMEM = "\x1b" "J[XOXPYPYOXNUMRMONNONQORVVWW RNPOQVUWVWYVZS[P[MZLYLXMXMY";
const char glyph116[] PROGMEM = "\x11" "KYTFPTOXOZP[S[UYVW RUFQTPXPZQ[ RNMWM";
const char glyph117[] PROGMEM = "\x24" "F]GQHOJMMMNNNQLWLYN[ RLMMNMQKWKYLZN[P[RZTXVT RXMVTUXUZV[Y[[Y\\W RYMWTVXVZW[";
const char glyph118[] PROGMEM = "\x19" "H\\IQJOLMOMPNPQNWNYP[ RNMONOQMWMYNZP[Q[TZVXXUYQYMXMYO";
const char glyph119[] PROGMEM = "\x28" "C`DQEOGMJMKNKQIWIYK[ RIMJNJQHWHYIZK[M[OZQXRV RTMRVRYSZU[W[YZ[X\\V]R]M\\M]O RUMSVSYU[";
const char glyph120[] PROGMEM = "\x29" "H\\KQMNOMRMSOSR RQMRORRQVPXNZL[K[JZJYKXLYKZ RQVQYR[U[WZYW RYNXOYPZOZNYMXMVNTPSRRVRYS[";
const char glyph121[] PROGMEM = "\x28" "G\\HQIOKMNMONOQMWMYO[ RMMNNNQLWLYMZO[Q[SZUXWT RZMV[U^SaPbMbKaJ`J_K^L_K` RYMU[T^RaPb";
const char glyph122[] PROGMEM = "\x1e" "H\\YMXOVQNWLYK[ RLQMOOMRMVO RMOONRNVOXO RLYNYRZUZWY RNYR[U[WYXW";
const char glyph123[] PROGMEM = "\x27" "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
const char glyph124[] PROGMEM = "\x02" "NVRBRb";
const char glyph125[] PROGMEM = "\x27" "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
const char glyph126[] PROGMEM = "\x17" "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
const char glyph127[] PROGMEM = "\x22" "JZJFJ[K[KFLFL[M[MFNFN[O[OFPFP[Q[QFRFR[S[SFTFT[U[UFVFV[W[WFXFX[Y[YFZFZ[";

const char *const font[96] PROGMEM =
{
	glyph032, glyph033, glyph034, glyph035, glyph036, glyph037, glyph038, glyph039, 
	glyph040, glyph041, glyph042, glyph043, glyph044, glyph045, glyph046, glyph047, 
	glyph048, glyph049, glyph050, glyph051, glyph052, glyph053, glyph054, glyph055, 
	glyph056, glyph057, glyph058, glyph059, glyph060, glyph061, glyph062, glyph063, 
	glyph064, glyph065, glyph066, glyph067, glyph068, glyph069, glyph070, glyph071, 
	glyph072, glyph073, glyph074, glyph075, glyph076, glyph077, glyph078, glyph079, 
	glyph080, glyph081, glyph082, glyph083, glyph084, glyph085, glyph086, glyph087, 
	glyph088, glyph089, glyph090, glyph091, glyph092, glyph093, glyph094, glyph095, 
	glyph096, glyph097, glyph098, glyph099, glyph100, glyph101, glyph102, glyph103, 
	glyph104, glyph105, glyph106, glyph107, glyph108, glyph109, glyph110, glyph111, 
	glyph112, glyph113, glyph114, glyph115, glyph116, glyph117, glyph118, glyph119, 
	glyph120, glyph121, glyph122, glyph123, glyph124, glyph125, glyph126, glyph127
	
};
