//
// Hershey Font: scripts 
//
// USE RESTRICTION:
//    This distribution of the Hershey Fonts may be used by anyone for
//    any purpose, commercial or otherwise, providing that:
//
//        1. The following acknowledgements must be distributed with the font data:
//
//            - The Hershey Fonts were originally created by Dr.
//                A. V. Hershey while working at the U. S. National Bureau of Standards.
//            - The format of the Font data in this distribution was originally created by
//                James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821,
//               (mit-eddie!ci-dandelion!hurt)
//
//        2. The font data in this distribution may be converted into
//            any other format *EXCEPT* the format distributed by
//            the U.S. NTIS (which organization holds the rights
//            to the distribution and use of the font data in that
//            particular format). Not that anybody would really
//            *want* to use their format... each point is described
//            in eight bytes as "xxx yyy:", where xxx and yyy are
//            the coordinate values as ASCII numbers.
//

const char glyph032[] PROGMEM = "\x00" "JZ";
const char glyph033[] PROGMEM = "\x10" "MXUFTGRS RUGRS RUFVGRS RPYOZP[QZPY";
const char glyph034[] PROGMEM = "\x0b" "I[PFNM RQFNM RYFWM RZFWM";
const char glyph035[] PROGMEM = "\x0b" "H]SBLb RYBRb RLOZO RKUYU";
const char glyph036[] PROGMEM = "\x28" "H]TBL_ RYBQ_ RZJYKZL[K[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJVKULVKW";
const char glyph037[] PROGMEM = "\x1f" "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
const char glyph038[] PROGMEM = "\x36" "E_\\N[O\\P]O]N\\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPRQUSXUZW[Y[ZYZX RK[IZHXHVITJSPP ROLPQQTSWUYWZYZZY";
const char glyph039[] PROGMEM = "\x07" "MXUHTGUFVGVHUJSL";
const char glyph040[] PROGMEM = "\x13" "KZZBVESHQKOONTNXO]P`Qb RVESIQMPPOUOZP_Qb";
const char glyph041[] PROGMEM = "\x13" "JYSBTDUGVLVPUUSYQ\\N_Jb RSBTEUJUOTTSWQ[N_";
const char glyph042[] PROGMEM = "\x08" "J[TFTR ROIYO RYIOO";
const char glyph043[] PROGMEM = "\x05" "E_RIR[ RIR[R";
const char glyph044[] PROGMEM = "\x07" "MXP[OZPYQZQ[P]N_";
const char glyph045[] PROGMEM = "\x02" "E_IR[R";
const char glyph046[] PROGMEM = "\x05" "MWRYQZR[SZRY";
const char glyph047[] PROGMEM = "\x02" "G]_BEb";
const char glyph048[] PROGMEM = "\x29" "H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RTFRGPINLMOLSLVMYO[ RQ[SZUXWUXRYNYKXHVF";
const char glyph049[] PROGMEM = "\x0e" "H]TJO[ RVFP[ RVFSIPKNL RUIQKNL";
const char glyph050[] PROGMEM = "\x29" "H]OJPKOLNKNJOHPGSFVFYGZIZKYMWOTQPSMUKWI[ RVFXGYIYKXMVOPS RJYKXMXRZUZWYXW RMXR[U[WZXW";
const char glyph051[] PROGMEM = "\x31" "H]OJPKOLNKNJOHPGSFVFYGZIZKYMVOSP RVFXGYIYKXMVO RQPSPVQWRXTXWWYVZS[O[LZKYJWJVKULVKW RSPUQVRWTWWVYUZS[";
const char glyph052[] PROGMEM = "\x09" "H]XGR[ RYFS[ RYFJUZU";
const char glyph053[] PROGMEM = "\x26" "H]QFLP RQF[F RQGVG[F RLPMOPNSNVOWPXRXUWXUZR[O[LZKYJWJVKULVKW RSNUOVPWRWUVXTZR[";
const char glyph054[] PROGMEM = "\x2d" "H]YIXJYKZJZIYGWFTFQGOIMLLOKSKWLYMZO[R[UZWXXVXSWQVPTOQOOPMRLT RTFRGPINLMOLSLXMZ RR[TZVXWVWRVP";
const char glyph055[] PROGMEM = "\x1d" "H]NFLL R[FZIXLSRQUPWO[ RXLRRPUOWN[ RMIPFRFWI RNHPGRGWIYIZH[F";
const char glyph056[] PROGMEM = "\x3e" "H]SFPGOHNJNMOOQPTPXOYNZLZIYGVFSF RSFQGPHOJOMPOQP RTPWOXNYLYIXGVF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RQPNQLSKUKXLZN[ RR[UZVYWWWSVQ";
const char glyph057[] PROGMEM = "\x2d" "H]YMXOVQTRQROQNPMNMKNIPGSFVFXGYHZJZNYRXUVXTZQ[N[LZKXKWLVMWLX ROQNONKOIQGSF RXGYIYNXRWUUXSZQ[";
const char glyph058[] PROGMEM = "\x0a" "MXSMRNSOTNSM RPYOZP[QZ";
const char glyph059[] PROGMEM = "\x0d" "MXSMRNSOTNSM RP[OZPYQZQ[P]N_";
const char glyph060[] PROGMEM = "\x03" "F^ZIJRZ[";
const char glyph061[] PROGMEM = "\x05" "E_IO[O RIU[U";
const char glyph062[] PROGMEM = "\x03" "F^JIZRJ[";
const char glyph063[] PROGMEM = "\x21" "H]OJPKOLNKNJOHPGSFWFZG[I[KZMYNSPQQQSRTTT RWFYGZIZKYMXNVO RPYOZP[QZPY";
const char glyph064[] PROGMEM = "\x37" "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
const char glyph065[] PROGMEM = "\x13" "G[G[IZLWOSSLVFV[UXSUQSNQLQKRKTLVNXQZT[Y[";
const char glyph066[] PROGMEM = "\x28" "F]SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFXFZG[I[KZMYNWOTP RSPTPWQXRYTYWXYWZU[R[PZOX";
const char glyph067[] PROGMEM = "\x17" "H\\TLTMUNWNYMZKZIYGWFTFQGOIMLLNKRKVLYMZO[Q[TZVXWV";
const char glyph068[] PROGMEM = "\x22" "G^TFRGQIPMOSNVMXKZI[G[FZFXGWIWKXMZP[S[VZXXZT[O[KZHYGWFTFRHRJSMUPWRZT\\U";
const char glyph069[] PROGMEM = "\x1b" "H\\VJVKWLYLZKZIYGVFRFOGNINLONPOSPPPMQLRKTKWLYMZP[S[VZXXYV";
const char glyph070[] PROGMEM = "\x1b" "H\\RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV RQPZP";
const char glyph071[] PROGMEM = "\x1c" "G^G[IZMVPQQNRJRGQFPFOGNINLONQOUOXNYMZKZQYVXXVZS[O[LZJXIVIT";
const char glyph072[] PROGMEM = "\x25" "F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX RMRVOXN[L]J^H^G]F\\FZHXLVRUWUZV[W[YZZY\\V";
const char glyph073[] PROGMEM = "\x18" "IZWVUTSQROQLQIRGSFUFVGWIWLVQTVSXQZO[M[KZJXJVKUMUOV";
const char glyph074[] PROGMEM = "\x18" "JYT^R[PVOPOJPGRFTFUGVJVMURR[PaOdNfLgKfKdLaN^P\\SZWX";
const char glyph075[] PROGMEM = "\x26" "F^MMKLJJJIKGMFNFPGQIQKPONULYJ[H[GZGX R^I^G]F\\FZGXIVLTNROPO RROSQSXTZU[V[XZYY[V";
const char glyph076[] PROGMEM = "\x1c" "I\\MRORSQVOXMYKYHXFVFUGTISNRSQVPXNZL[J[IZIXJWLWNXQZT[V[YZ[X";
const char glyph077[] PROGMEM = "\x2c" "@aEMCLBJBICGEFFFHGIIIKHPGTE[ RGTJLLHMGOFPFRGSISKRPQTO[ RQTTLVHWGYFZF\\G]I]K\\PZWZZ[[\\[^Z_YaV";
const char glyph078[] PROGMEM = "\x1f" "E]JMHLGJGIHGJFKFMGNINKMPLTJ[ RLTOLQHRGTFVFXGYIYKXPVWVZW[X[ZZ[Y]V";
const char glyph079[] PROGMEM = "\x1c" "H]TFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGVFTFRHRKSNUQWSZU\\V";
const char glyph080[] PROGMEM = "\x1e" "F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFZF\\G]H^J^M]O\\PZQWQUPTO";
const char glyph081[] PROGMEM = "\x1f" "H^ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[YZ[X";
const char glyph082[] PROGMEM = "\x25" "F_SHTITLSPRSQUOXMZK[J[IZIWJRKOLMNJPHRGUFYF[G\\H]J]M\\O[PYQVQSPTQUSUXVZX[ZZ[Y]V";
const char glyph083[] PROGMEM = "\x1b" "H\\H[JZLXOTQQSMTJTGSFRFQGPIPKQMSOVQXSYUYWXYWZT[P[MZKXJVJT";
const char glyph084[] PROGMEM = "\x18" "H[RLPLNKMINGQFTFXG[G]F RXGVNTTRXPZN[L[JZIXIVJULUNV";
const char glyph085[] PROGMEM = "\x20" "E]JMHLGJGIHGJFKFMGNINKMOLRKVKXLZN[P[RZSYUUXMZF RXMWQVWVZW[X[ZZ[Y]V";
const char glyph086[] PROGMEM = "\x1f" "F]KMILHJHIIGKFLFNGOIOKNOMRLVLYM[O[QZTWVTXPYMZIZGYFXFWGVIVKWNYP[Q";
const char glyph087[] PROGMEM = "\x18" "C_HMFLEJEIFGHFIFKGLILLK[ RUFK[ RUFS[ RaF_G\\JYNVTS[";
const char glyph088[] PROGMEM = "\x23" "F^NLLLKKKILGNFPFRGSISLQUQXRZT[V[XZYXYVXUVU R]I]G\\FZFXGVITLPUNXLZJ[H[GZGX";
const char glyph089[] PROGMEM = "\x25" "F]KMILHJHIIGKFLFNGOIOKNOMRLVLXMZN[P[RZTXVUWSYM R[FYMVWT]RbPfNgMfMdNaP^S[VY[V";
const char glyph090[] PROGMEM = "\x27" "H]ULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWTTWPZN[K[JZJXKWNWPXQYR[R^QaPcNfLgKfKdLaN^Q[TYZV";
const char glyph091[] PROGMEM = "\x0b" "KYOBOb RPBPb ROBVB RObVb";
const char glyph092[] PROGMEM = "\x02" "KYKFY^";
const char glyph093[] PROGMEM = "\x0b" "KYTBTb RUBUb RNBUB RNbUb";
const char glyph094[] PROGMEM = "\x0a" "JZPLRITL RMORJWO RRJR[";
const char glyph095[] PROGMEM = "\x02" "JZJ]Z]";
const char glyph096[] PROGMEM = "\x07" "MXVFTHSJSKTLUKTJ";
const char glyph097[] PROGMEM = "\x15" "L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXVRUWUZV[W[YZZY\\V";
const char glyph098[] PROGMEM = "\x16" "M[MVOSRNSLTITGSFQGPIOMNTNZO[P[RZTXUUURVVWWYW[V";
const char glyph099[] PROGMEM = "\x0d" "MXTTTSSRQROSNTMVMXNZP[S[VYXV";
const char glyph100[] PROGMEM = "\x17" "L\\UUTSRRPRNSMTLVLXMZO[Q[SZTXZF RVRUWUZV[W[YZZY\\V";
const char glyph101[] PROGMEM = "\x10" "NXOYQXRWSUSSRRQROSNUNXOZQ[S[UZVYXV";
const char glyph102[] PROGMEM = "\x17" "OWOVSQUNVLWIWGVFTGSIQQNZKaJdJfKgMfNcOZP[R[TZUYWV";
const char glyph103[] PROGMEM = "\x1b" "L[UUTSRRPRNSMTLVLXMZO[Q[SZTY RVRTYPdOfMgLfLdMaP^S\\U[XY[V";
const char glyph104[] PROGMEM = "\x1c" "M\\MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUUXUZV[W[YZZY\\V";
const char glyph105[] PROGMEM = "\x0f" "PWSMSNTNTMSM RPVRRPXPZQ[R[TZUYWV";
const char glyph106[] PROGMEM = "\x13" "PWSMSNTNTMSM RPVRRLdKfIgHfHdIaL^O\\Q[TYWV";
const char glyph107[] PROGMEM = "\x20" "M[MVOSRNSLTITGSFQGPIOMNSM[ RM[NXOVQSSRURVSVUTVQV RQVSWTZU[V[XZYY[V";
const char glyph108[] PROGMEM = "\x11" "OWOVQSTNULVIVGUFSGRIQMPTPZQ[R[TZUYWV";
const char glyph109[] PROGMEM = "\x20" "E^EVGSIRJSJTIXH[ RIXJVLSNRPRQSQTPXO[ RPXQVSSURWRXSXUWXWZX[Y[[Z\\Y^V";
const char glyph110[] PROGMEM = "\x16" "J\\JVLSNROSOTNXM[ RNXOVQSSRURVSVUUXUZV[W[YZZY\\V";
const char glyph111[] PROGMEM = "\x16" "LZRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXWXYWZV";
const char glyph112[] PROGMEM = "\x17" "KZKVMSNQMUGg RMUNSPRRRTSUUUWTYSZQ[ RMZO[R[UZWYZV";
const char glyph113[] PROGMEM = "\x1a" "L[UUTSRRPRNSMTLVLXMZO[Q[SZ RVRUUSZPaOdOfPgRfScS\\U[XY[V";
const char glyph114[] PROGMEM = "\x0e" "MZMVOSPQPSSSTTTVSYSZT[U[WZXYZV";
const char glyph115[] PROGMEM = "\x0f" "NYNVPSQQQSSVTXTZR[ RNZP[T[VZWYYV";
const char glyph116[] PROGMEM = "\x0f" "OXOVQSSO RVFPXPZQ[S[UZVYXV RPNWN";
const char glyph117[] PROGMEM = "\x12" "L[LVNRLXLZM[O[QZSXUU RVRTXTZU[V[XZYY[V";
const char glyph118[] PROGMEM = "\x10" "L[LVNRMWMZN[O[RZTXUUUR RURVVWWYW[V";
const char glyph119[] PROGMEM = "\x18" "I^LRJTIWIYJ[L[NZPX RRRPXPZQ[S[UZWXXUXR RXRYVZW\\W^V";
const char glyph120[] PROGMEM = "\x13" "JZJVLSNRPRQSQZR[U[XYZV RWSVRTRSSOZN[L[KZ";
const char glyph121[] PROGMEM = "\x16" "L[LVNRLXLZM[O[QZSXUU RVRPdOfMgLfLdMaP^S\\U[XY[V";
const char glyph122[] PROGMEM = "\x16" "LZLVNSPRRRTTTVSXQZN[P\\Q^QaPdOfMgLfLdMaP^S\\WYZV";
const char glyph123[] PROGMEM = "\x27" "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
const char glyph124[] PROGMEM = "\x02" "NVRBRb";
const char glyph125[] PROGMEM = "\x27" "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
const char glyph126[] PROGMEM = "\x17" "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
const char glyph127[] PROGMEM = "\x0d" "KYQFOGNINKOMQNSNUMVKVIUGSFQF";

const char *const font[96] PROGMEM =
{
	glyph032, glyph033, glyph034, glyph035, glyph036, glyph037, glyph038, glyph039, 
	glyph040, glyph041, glyph042, glyph043, glyph044, glyph045, glyph046, glyph047, 
	glyph048, glyph049, glyph050, glyph051, glyph052, glyph053, glyph054, glyph055, 
	glyph056, glyph057, glyph058, glyph059, glyph060, glyph061, glyph062, glyph063, 
	glyph064, glyph065, glyph066, glyph067, glyph068, glyph069, glyph070, glyph071, 
	glyph072, glyph073, glyph074, glyph075, glyph076, glyph077, glyph078, glyph079, 
	glyph080, glyph081, glyph082, glyph083, glyph084, glyph085, glyph086, glyph087, 
	glyph088, glyph089, glyph090, glyph091, glyph092, glyph093, glyph094, glyph095, 
	glyph096, glyph097, glyph098, glyph099, glyph100, glyph101, glyph102, glyph103, 
	glyph104, glyph105, glyph106, glyph107, glyph108, glyph109, glyph110, glyph111, 
	glyph112, glyph113, glyph114, glyph115, glyph116, glyph117, glyph118, glyph119, 
	glyph120, glyph121, glyph122, glyph123, glyph124, glyph125, glyph126, glyph127
	
};
