//
// Hershey Font: scriptc 
//
// USE RESTRICTION:
//    This distribution of the Hershey Fonts may be used by anyone for
//    any purpose, commercial or otherwise, providing that:
//
//        1. The following acknowledgements must be distributed with the font data:
//
//            - The Hershey Fonts were originally created by Dr.
//                A. V. Hershey while working at the U. S. National Bureau of Standards.
//            - The format of the Font data in this distribution was originally created by
//                James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821,
//               (mit-eddie!ci-dandelion!hurt)
//
//        2. The font data in this distribution may be converted into
//            any other format *EXCEPT* the format distributed by
//            the U.S. NTIS (which organization holds the rights
//            to the distribution and use of the font data in that
//            particular format). Not that anybody would really
//            *want* to use their format... each point is described
//            in eight bytes as "xxx yyy:", where xxx and yyy are
//            the coordinate values as ASCII numbers.
//

const char glyph032[] PROGMEM = "\x00" "JZ";
const char glyph033[] PROGMEM = "\x10" "MXUFTGRS RUGRS RUFVGRS RPYOZP[QZPY";
const char glyph034[] PROGMEM = "\x0b" "I[PFNM RQFNM RYFWM RZFWM";
const char glyph035[] PROGMEM = "\x0b" "H]SFLb RYFRb RLQZQ RKWYW";
const char glyph036[] PROGMEM = "\x28" "H]TBL_ RYBQ_ RZJYKZL[K[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZS[O[LZKYJWJVKULVKW";
const char glyph037[] PROGMEM = "\x1f" "F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
const char glyph038[] PROGMEM = "\x36" "E_\\N[O\\P]O]N\\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPRQUSXUZW[Y[ZYZX RK[IZHXHVITJSPP ROLPQQTSWUYWZYZZY";
const char glyph039[] PROGMEM = "\x07" "MXUHTGUFVGVHUJSL";
const char glyph040[] PROGMEM = "\x13" "KZZBVESHQKOONTNXO]P`Qb RVESIQMPPOUOZP_Qb";
const char glyph041[] PROGMEM = "\x13" "JYSBTDUGVLVPUUSYQ\\N_Jb RSBTEUJUOTTSWQ[N_";
const char glyph042[] PROGMEM = "\x08" "J[TFTR ROIYO RYIOO";
const char glyph043[] PROGMEM = "\x05" "E_RIR[ RIR[R";
const char glyph044[] PROGMEM = "\x07" "MXP[OZPYQZQ[P]N_";
const char glyph045[] PROGMEM = "\x02" "E_IR[R";
const char glyph046[] PROGMEM = "\x05" "MXPYOZP[QZPY";
const char glyph047[] PROGMEM = "\x02" "G]_BEb";
const char glyph048[] PROGMEM = "\x29" "H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RTFRGPINLMOLSLVMYO[ RQ[SZUXWUXRYNYKXHVF";
const char glyph049[] PROGMEM = "\x0e" "H]TJO[ RVFP[ RVFSIPKNL RUIQKNL";
const char glyph050[] PROGMEM = "\x29" "H]OJPKOLNKNJOHPGSFVFYGZIZKYMWOTQPSMUKWI[ RVFXGYIYKXMVOPS RJYKXMXRZUZWYXW RMXR[U[WZXW";
const char glyph051[] PROGMEM = "\x31" "H]OJPKOLNKNJOHPGSFVFYGZIZKYMVOSP RVFXGYIYKXMVO RQPSPVQWRXTXWWYVZS[O[LZKYJWJVKULVKW RSPUQVRWTWWVYUZS[";
const char glyph052[] PROGMEM = "\x09" "H]XGR[ RYFS[ RYFJUZU";
const char glyph053[] PROGMEM = "\x26" "H]QFLP RQF[F RQGVG[F RLPMOPNSNVOWPXRXUWXUZR[O[LZKYJWJVKULVKW RSNUOVPWRWUVXTZR[";
const char glyph054[] PROGMEM = "\x2d" "H]YIXJYKZJZIYGWFTFQGOIMLLOKSKWLYMZO[R[UZWXXVXSWQVPTOQOOPMRLT RTFRGPINLMOLSLXMZ RR[TZVXWVWRVP";
const char glyph055[] PROGMEM = "\x1d" "H]NFLL R[FZIXLSRQUPWO[ RXLRRPUOWN[ RMIPFRFWI RNHPGRGWIYIZH[F";
const char glyph056[] PROGMEM = "\x3e" "H]SFPGOHNJNMOOQPTPXOYNZLZIYGVFSF RSFQGPHOJOMPOQP RTPWOXNYLYIXGVF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RQPNQLSKUKXLZN[ RR[UZVYWWWSVQ";
const char glyph057[] PROGMEM = "\x2d" "H]YMXOVQTRQROQNPMNMKNIPGSFVFXGYHZJZNYRXUVXTZQ[N[LZKXKWLVMWLX ROQNONKOIQGSF RXGYIYNXRWUUXSZQ[";
const char glyph058[] PROGMEM = "\x0a" "MXSMRNSOTNSM RPYOZP[QZ";
const char glyph059[] PROGMEM = "\x0d" "MXSMRNSOTNSM RP[OZPYQZQ[P]N_";
const char glyph060[] PROGMEM = "\x03" "F^ZIJRZ[";
const char glyph061[] PROGMEM = "\x05" "E_IO[O RIU[U";
const char glyph062[] PROGMEM = "\x03" "F^JIZRJ[";
const char glyph063[] PROGMEM = "\x21" "H]OJPKOLNKNJOHPGSFWFZG[I[KZMYNSPQQQSRTTT RWFYGZIZKYMXNVO RPYOZP[QZPY";
const char glyph064[] PROGMEM = "\x37" "E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
const char glyph065[] PROGMEM = "\x25" "E\\XFVHTKQPOSLWIZG[E[DZDXEWFXEY RXFWJUTT[ RXFU[ RT[TYSVRTPRNQLQKRKTLWOZR[V[XZ";
const char glyph066[] PROGMEM = "\x45" "F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFXFZG[I[KZMXNTORO RXFYGZIZKYMXN RTOWPXQYSYVXYWZU[S[RZRXSU RTOVPWQXSXVWYU[";
const char glyph067[] PROGMEM = "\x28" "H]KHJJJLKNNOQOUNWMYKZIZGYFWFTGQJOMMQLULXMZP[R[UZWXXVXTWRURSSRU RWFUGRJPMNQMUMXNZP[";
const char glyph068[] PROGMEM = "\x2a" "F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWJWLXNZP[S[UZWXYTZOZLYIWGUFPFMGKIJKJMKNMNNMOK";
const char glyph069[] PROGMEM = "\x30" "I\\WIVJVLWMYMZKZIYGWFTFRGQHPJPLQNSO RTFRHQJQMSO RSOQONPLRKTKWLYMZO[R[UZWXXVXTWRURSSRU RQOOPMRLTLXMZ";
const char glyph070[] PROGMEM = "\x2d" "G\\WHVJTORUQWOZM[ RQLPNNOLOKMKKLINGQF[FXGWHVKTSSVRXPZM[K[IZHYHXIWJXIY RSFWGXG ROSPRRQVQXPZMXT";
const char glyph071[] PROGMEM = "\x34" "G]JIIKIMJOLPOPROTNWKXHXGWFVFTGRIQKPNPQQSSTUTWSYQZO RWFUGSIRKQNQRST RZOYSWWUYSZO[L[JZIXIWJVKWJX RYSWVUXRZO[";
const char glyph072[] PROGMEM = "\x36" "F^LLKKKILGOFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RJTKSMRVOXN[L]J^H^G]F\\FZGXJWLURTVTYV[W[YZ[X R\\FZHXLVRUVUYV[";
const char glyph073[] PROGMEM = "\x20" "IYWHUKSPQUPWNZL[ RYLWNTOQOONNLNJOHQGUFYFWHVJTPRVQXOZL[J[IZIXJWKXJY";
const char glyph074[] PROGMEM = "\x21" "IZYFWHUKSPPYN] RYMWOTPQPOONMNKOIQGUFYFWIVKSTQXPZN]M^K_J^J\\KZMXOWRVVU";
const char glyph075[] PROGMEM = "\x3a" "F^LLKKKIMGPFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RZGWKUMSNPO R]G\\H]I^H^G]F\\FZGWLVMTNPO RPOSPTRUYV[ RPORPSRTYV[W[YZ[X";
const char glyph076[] PROGMEM = "\x27" "I[MILKLMMOOPRPUOWNZK[H[GZFYFWGVHTKPUOWMZK[ RVHTLRSQVPXNZK[I[HZHXIWKWMXPZR[U[WZYX";
const char glyph077[] PROGMEM = "\x30" "D`RFNOKUIXGZE[C[BZBXCWDXCY RRFPMOQNVNZP[ RRFQJPOOVOZP[ R[FWORXP[ R[FYMXQWVWZY[Z[\\Z^X R[FZJYOXVXZY[";
const char glyph078[] PROGMEM = "\x25" "G^RFQJOPMULWJZH[F[EZEXFWGXFY RRFRKSVT[ RRFSKTVT[ R`G_H`IaHaG`F^F\\GZJYLWQUWT[";
const char glyph079[] PROGMEM = "\x21" "H]SFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGWGUHSJQNPSPV RQGOJMNLRLVMYO[";
const char glyph080[] PROGMEM = "\x34" "F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFVFYGZH[J[MZOYPVQTQRP RVFXGYHZJZMYOXPVQ";
const char glyph081[] PROGMEM = "\x2a" "H]UJULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[XZZX RWFXGYIYMXPVSSVOYK[";
const char glyph082[] PROGMEM = "\x40" "F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMHOGRFWFZG[I[KZMYNVORO RWFYGZIZKYMXNVO RROUPVRWYX[ RROTPURVYX[Y[[Z]X";
const char glyph083[] PROGMEM = "\x23" "H\\NIMKMMNOPPSPVOXN[K\\H\\G[FZFXGWHVJUMSTRWPZN[ RVJUNTUSXQZN[K[IZHXHWIVJWIX";
const char glyph084[] PROGMEM = "\x25" "I[YHXJVOTUSWQZO[ RSLRNPONOMMMKNIPGSF\\FZGYHXKVSUVTXRZO[M[KZJYJXKWLXKY RUFYGZG";
const char glyph085[] PROGMEM = "\x26" "G]HJJGLFMFOHOKNNKVKYL[ RMFNHNKKSJVJYL[N[PZSWUTVR RZFVRUVUYW[X[ZZ\\X R[FWRVVVYW[";
const char glyph086[] PROGMEM = "\x23" "G\\HJJGLFMFOHOKNOLVLYM[ RMFNHNKLRKVKYM[N[QZTWVTXPYMZIZGYFXFWGVIVLWNYP[Q]Q";
const char glyph087[] PROGMEM = "\x28" "F]ILHLGKGIHGJFNFMHLLKUJ[ RLLLUK[ RVFTHRLOUMYK[ RVFUHTLSUR[ RTLTUS[ R`F^G\\IZLWUUYS[";
const char glyph088[] PROGMEM = "\x33" "H\\PKOLMLLKLIMGOFQFSGTITLSPQUOXMZJ[H[GZGXHWIXHY RQFRGSISLRPPUNXLZJ[ R]G\\H]I^H^G]F[FYGWIULSPRURXSZT[U[WZYX";
const char glyph089[] PROGMEM = "\x29" "G]JJLGNFOFQGQIOOORPT ROFPGPINONRPTRTUSWQYNZL R\\FZLWTUX R]F[LYQWUUXSZP[L[JZIXIWJVKWJX";
const char glyph090[] PROGMEM = "\x2b" "G\\ZHYJWOVRUTSWQYOZL[ RSLRNPONOMMMKNIPGSF]F[GZHYKXOVUTXQZL[H[GZGXHWJWLXOZQ[T[WZYX RVFZG[G";
const char glyph091[] PROGMEM = "\x0b" "KYOBOb RPBPb ROBVB RObVb";
const char glyph092[] PROGMEM = "\x02" "KYKFY^";
const char glyph093[] PROGMEM = "\x0b" "KYTBTb RUBUb RNBUB RNbUb";
const char glyph094[] PROGMEM = "\x0a" "JZPLRITL RMORJWO RRJR[";
const char glyph095[] PROGMEM = "\x02" "JZJ]Z]";
const char glyph096[] PROGMEM = "\x07" "MXVFTHSJSKTLUKTJ";
const char glyph097[] PROGMEM = "\x20" "K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRTXTZV[XZYY[V RWRUXUZV[";
const char glyph098[] PROGMEM = "\x16" "LZLVNSPO RSFMXMZO[P[RZTXUUURVVWWXWZV RTFNXNZO[";
const char glyph099[] PROGMEM = "\x15" "LXTSSTTTTSSRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[";
const char glyph100[] PROGMEM = "\x20" "K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RZFTXTZV[XZYY[V R[FUXUZV[";
const char glyph101[] PROGMEM = "\x16" "LXOYQXRWSUSSRRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[";
const char glyph102[] PROGMEM = "\x1a" "OXRRUOWLXIXGWFUGTIKdKfLgNfOcPZQ[S[UZVYXV RTISNRRO[M`Kd";
const char glyph103[] PROGMEM = "\x25" "K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRPd RWRT[R`PdOfMgLfLdMaO_R]V[YY[V";
const char glyph104[] PROGMEM = "\x1d" "L[LVNSPO RSFL[ RTFM[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
const char glyph105[] PROGMEM = "\x12" "NVSLRMSNTMSL RQROXOZQ[SZTYVV RRRPXPZQ[";
const char glyph106[] PROGMEM = "\x17" "NVSLRMSNTMSL RQRKd RRRO[M`KdJfHgGfGdHaJ_M]Q[TYVV";
const char glyph107[] PROGMEM = "\x1e" "LZLVNSPO RSFL[ RTFM[ RURUSVSURTRRTOU ROURVSZT[ ROUQVRZT[U[XYZV";
const char glyph108[] PROGMEM = "\x10" "NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[";
const char glyph109[] PROGMEM = "\x2c" "E^EVGSIRKSKUI[ RIRJSJUH[ RKUMSORPRRSRUP[ RPRQSQUO[ RRUTSVRWRYSYUXXXZY[ RWRXSXUWXWZY[[Z\\Y^V";
const char glyph110[] PROGMEM = "\x1f" "I[IVKSMROSOUM[ RMRNSNUL[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
const char glyph111[] PROGMEM = "\x1c" "KYRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXVXXWYV RPRNTMVMYO[";
const char glyph112[] PROGMEM = "\x1d" "L[LVNSPO RQLHg RRLIg ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V";
const char glyph113[] PROGMEM = "\x22" "K[UUTSRRPRNSMTLVLXMZO[Q[SZ RPRNTMVMYO[ RVRPdPfQgSfTcT[V[YY[V RWRT[R`Pd";
const char glyph114[] PROGMEM = "\x17" "LZLVNSPRRSRUP[ RPRQSQUO[ RRUTSVRWRVU RVRVUWWXWZV";
const char glyph115[] PROGMEM = "\x15" "NZNVPSQQQSTUUWUYTZR[ RQSSUTWTYR[ RNZP[U[XYZV";
const char glyph116[] PROGMEM = "\x13" "NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[ RPNVN";
const char glyph117[] PROGMEM = "\x1a" "K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRTXTZV[XZYY[V RWRUXUZV[";
const char glyph118[] PROGMEM = "\x16" "KZNRMTLWLZN[O[RZTXUUUR RORNTMWMZN[ RURVVWWXWZV";
const char glyph119[] PROGMEM = "\x23" "H]LRJTIWIZK[L[NZPX RMRKTJWJZK[ RRRPXPZR[S[UZWXXUXR RSRQXQZR[ RXRYVZW[W]V";
const char glyph120[] PROGMEM = "\x29" "JZJVLSNRPRQSQUPXOZM[L[KZKYLYKZ RWSVTWTWSVRURSSRUQXQZR[U[XYZV RQSRU RSSQU RPXQZ RQXOZ";
const char glyph121[] PROGMEM = "\x1f" "K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRPd RWRT[R`PdOfMgLfLdMaO_R]V[YY[V";
const char glyph122[] PROGMEM = "\x25" "LYLVNSPRRRTSTVSXPZN[ RRRSSSVRXPZ RN[P\\Q^QaPdNfLgKfKdLaO^R\\VYYV RN[O\\P^PaOdNf";
const char glyph123[] PROGMEM = "\x27" "KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
const char glyph124[] PROGMEM = "\x02" "NVRBRb";
const char glyph125[] PROGMEM = "\x27" "KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
const char glyph126[] PROGMEM = "\x17" "F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
const char glyph127[] PROGMEM = "\x0d" "KZSFQGPIPKQMSNUNWMXKXIWGUFSF";

const char *const font[96] PROGMEM =
{
	glyph032, glyph033, glyph034, glyph035, glyph036, glyph037, glyph038, glyph039, 
	glyph040, glyph041, glyph042, glyph043, glyph044, glyph045, glyph046, glyph047, 
	glyph048, glyph049, glyph050, glyph051, glyph052, glyph053, glyph054, glyph055, 
	glyph056, glyph057, glyph058, glyph059, glyph060, glyph061, glyph062, glyph063, 
	glyph064, glyph065, glyph066, glyph067, glyph068, glyph069, glyph070, glyph071, 
	glyph072, glyph073, glyph074, glyph075, glyph076, glyph077, glyph078, glyph079, 
	glyph080, glyph081, glyph082, glyph083, glyph084, glyph085, glyph086, glyph087, 
	glyph088, glyph089, glyph090, glyph091, glyph092, glyph093, glyph094, glyph095, 
	glyph096, glyph097, glyph098, glyph099, glyph100, glyph101, glyph102, glyph103, 
	glyph104, glyph105, glyph106, glyph107, glyph108, glyph109, glyph110, glyph111, 
	glyph112, glyph113, glyph114, glyph115, glyph116, glyph117, glyph118, glyph119, 
	glyph120, glyph121, glyph122, glyph123, glyph124, glyph125, glyph126, glyph127
	
};

#define FONT_INCLUDED
